(function(z){
var kH=function(a,b){return a.da.m(b?a.tJ:a.xE)};var lH=function(a){if(z.B&&!(9<=z.Ug)){var b=!1;try{b=a.parentNode}catch(c){}return!!b}return z.mf(a.ownerDocument.body,a)};var mH=function(a){z.yc.call(this);this.tJ=z.hp();this.xE=z.hp();this.sA=a.Wg();this.da=z.H(a.ua());a.sh(this.da.B("SPAN",{id:this.tJ}),this.da.B("SPAN",{id:this.xE}))};var nH=function(a,b){var c=b.ld();a.Pb[c]=b;for(var d in z.tz)b[z.tz[d]]&&a.Hj[d].push(b);b.F=a;a.uc()&&b.enable(a)};
var oH=function(a){return a.F&&z.Hc?(a=a.F.eb.Ta(),a.scrollTo.bind(a,a.scrollX,a.scrollY)):function(){}};var pH=function(a){return a.F&&a.F.eb};var qH=function(a){var b=a.node.parentNode;return new z.Ju(b,z.mb(b.childNodes,a.node))};var rH=function(a,b,c,d){return z.bu(a,b,c,d)};var sH=function(a){return a.Z()&&a.la()?new mH(a):null};
var tH=function(a){var b;if(3==a.node.nodeType)for(b=a.node.previousSibling;b&&3==b.nodeType;b=b.previousSibling)a.offset+=z.Du(b);else b=a.node.previousSibling;var c=a.node.parentNode;a.node=b?b.nextSibling:c.firstChild;return a};var uH=function(a,b){return b?z.Iu(a.Z(),a.va()):z.Iu(a.la(),a.Ja())};var vH=function(a){for(var b=null,c=a.firstChild;c;){var d=c.nextSibling;3==c.nodeType?""==c.nodeValue?a.removeChild(c):b?(b.nodeValue+=c.nodeValue,a.removeChild(c)):b=c:(vH(c),b=null);c=d}};
var wH=function(a){var b=a&&a.nodeName;return!(!a||"block"!=(1!=a.nodeType?null:z.B?z.xg(a,"display"):z.wg(a,"display"))&&"TD"!=b&&"TABLE"!=b&&"LI"!=b)};
var xH=function(a){var b=a.Wg(),c=tH(uH(a,!b)),d=qH(c),f=c.node.previousSibling;3==c.node.nodeType&&(c.node=null);var g=tH(uH(a,b)),h=qH(g),k=g.node.previousSibling;3==g.node.nodeType&&(g.node=null);return function(){!c.node&&f&&(c.node=f.nextSibling,c.node||(c=new z.Ju(f,z.Du(f))));!g.node&&k&&(g.node=k.nextSibling,g.node||(g=new z.Ju(k,z.Du(k))));return z.bu(c.node||d.node.firstChild||d.node,c.offset,g.node||h.node.firstChild||h.node,g.offset)}};var yH=function(a){return z.vf(a,wH,!0)};
var zH=function(a,b){if(b)var c=xH(b),d=yH(b.Ob());d?(d=z.Jo(d,a),z.B?vH(d):d.normalize()):a&&(z.B?vH(a):a.normalize());return c?c():null};var AH=function(a,b,c){z.Vr.call(this,b,a||z.BD.ba(),c)};var BH=function(a){return a.getAttribute&&"true"==a.getAttribute("g_editable")};var CH=function(a){mH.call(this,a)};
var DH=function(a,b,c){for(var d=(b=1==b)?a.Z():a.la(),f=b?a.va():a.Ja(),g=a.Ob();d!=g&&d!=c&&!(b&&0!=f||!b&&f!=z.Du(d));)var h=d.parentNode,d=z.mb(h.childNodes,d),f=b?d:d+1,d=h;return rH(b?d:a.Z(),b?f:a.va(),b?a.la():d,b?a.Ja():f)};
var EH=function(a){z.xo(a,!1);if(z.VE){var b=a;for(a=a.parentNode;a&&"HTML"!=a.tagName;){if(z.em?"none"==a.style[z.em].toLowerCase():(z.B||z.vg)&&"on"==a.getAttribute("unselectable")){z.xo(a,!1,!0);for(var c=0,d=a.childNodes.length;c<d;c++){var f=a.childNodes[c];f!=b&&1==f.nodeType&&z.xo(a.childNodes[c],!0)}}b=a;a=a.parentNode}}};var FH=function(a){var b=a.target.tagName;"TEXTAREA"!=b&&"INPUT"!=b&&a.preventDefault()};
var GH=function(a){var b=z.Od(a);a=new z.Nd;var c=null;a.next=function(){for(;;){if(null==c){var a=b.next();c=z.Od(a)}try{return c.next()}catch(f){if(f!==z.Pd)throw f;c=null}}};return a};var HH=function(a){var b=a.Ob();return a.Z()!=b.parentElement&&BH(b)||!!z.vf(b,BH)};var IH=function(a,b){var c=DH(a,1,b),c=DH(c,0,b),d=c.Z(),f=c.la(),g=c.va(),c=c.Ja();if(d==f){for(;f!=b&&0==g&&c==z.Du(f);)d=f.parentNode,g=z.mb(d.childNodes,f),c=g+1,f=d;d=f}return z.bu(d,g,f,c)};
var JH=function(a,b){z.VE&&b.g(a,"mousedown",FH,!0);z.xo(a,!0);for(var c=a.getElementsByTagName("INPUT"),d=0,f=c.length;d<f;d++){var g=c[d];g.type in KH&&EH(g)}z.w(a.getElementsByTagName("TEXTAREA"),EH)};var LH=function(a,b,c){for(var d;a!=c&&(d=a.parentNode);){for(var f=d.cloneNode(!1);a.nextSibling;)f.appendChild(a.nextSibling);b&&f.insertBefore(b,f.firstChild);b=f;a=d}return b};var MH=function(a){return!!NH[a.tagName]};var OH=function(a){return z.zu(z.Wo(new z.wu(a),z.Au))};
var PH=function(a){return(a=String(a).toLowerCase())?z.qb([".jpg",".jpeg",".png"],function(b){return z.op(a,b)}):!1};var QH=function(a,b){var c=z.Od(a),d=new z.Nd;d.next=function(){var a=c.next();if(b.call(void 0,a,void 0,c))return a;throw z.Pd;};return d};var RH=function(a,b){var c=z.Od(a),d=new z.Nd,f=!0;d.next=function(){for(;;){var a=c.next();if(!f||!b.call(void 0,a,void 0,c))return f=!1,a}};return d};var SH=function(a){return GH(arguments)};
var TH=function(a,b){a=z.Od(a);try{for(;;)if(b.call(void 0,a.next(),void 0,a))return!0}catch(c){if(c!==z.Pd)throw c;}return!1};var UH=function(a){z.F.call(this);this.jd=a};var VH=function(a){this.gl=a;this.Ki=new z.Aj("",!0,this.gl.jd);this.gn=new z.Nj(this.gl.jd);this.en={};this.Dh("tr-dialog")};var WH=function(a,b){var c=z.u("OK");a.gn.set("ok",b||c,!0);a.en.ok=(0,z.q)(a.gl.sP,a.gl)};var XH=function(a,b){var c=z.Km,d=z.u("Cancel");a.gn.set(c,b||d,!1,!0);a.en[c]=(0,z.q)(a.gl.Tn,a.gl);return a};
var YH=function(a){a.gn.Vg()&&(WH(a),XH(a));z.Kj(a.Ki,a.gn);var b=a.en;a.en=null;a.Ki.g(z.Mj,function(a){if(b[a.key])return b[a.key](a)});a.Ki.Ap(!0);var c=a.Ki;a.Ki=null;return c};var $H=function(a){z.nz.call(this);this.YM=a;this.KI=function(){}};var aI=function(a){var b=a.F,c=a.VI;c&&c.restore();b.focus();a.VI=null};var bI=function(a){a.Ga&&!a.Ly&&(a.Ly=!0,a.Ga.H(),a.Ga=null,a.Ly=!1)};var cI=function(a){this.qe=a;this.ix=[]};
var dI=function(a){if(!a.Fw){var b=z.yu(a.qe);a.Fw=b.tagName&&"IMG"==b.tagName?b.getAttribute("alt"):z.Go(a.qe)}return a.Fw};var eI=function(a,b,c,d){var f=new cI(a);f.qe.href=b;c&&(a.target=c);d&&(f.ix=d);return f};var fI=function(a,b){var c=new cI(a),d;d=(0,z.cb)(dI(c));d=gI(d)?0>d.search(/:/)?"http://"+z.jp(d):d:hI.test(d)?"mailto:"+d:null;c.qe.href=d?d:"";b&&(a.target=b)};
var gI=function(a){if(/\s/.test(a)||hI.test(a))return!1;var b=!1;/^[^:\/?#.]+:/.test(a)||(a="http://"+a,b=!0);a=a.match(z.se);if(-1!=z.mb(["mailto","aim"],a[1]))return!0;var c=a[3];if(!c||b&&-1==c.indexOf(".")||/[^\w\d\-\u0100-\uffff.%]/.test(c))return!1;b=a[5];return!b||0==b.indexOf("/")};var iI=function(){z.nz.call(this)};var jI=function(a){return pH(a).ua()};
var kI=function(a){if(z.B||z.vg){var b=a.ze(),c=b.Ob(),d=jI(a);lI.lastIndex=0;lI.test(c.innerHTML)&&(a=sH(b),"P"==c.tagName?mI(c,!0):(b=c.innerHTML.replace(lI,'\x3cp$1 trtempbr\x3d"temp_br"\x3e'),z.Eu(c,b),c=z.wb(c.getElementsByTagName("P")),z.Qd(c,function(a){"temp_br"==a.getAttribute("trtempbr")&&(a.removeAttribute("trtempbr"),z.mp(z.pf(a))&&a.appendChild(z.B?d.createTextNode(" "):d.createElement("BR")),mI(a))})),a.restore())}};
var mI=function(a,b){if(z.B||z.vg){var c=a.outerHTML.replace(/<(\/?)p/gi,"\x3c$1div");b&&(c=c.replace(lI,"\x3c/div\x3e\x3cdiv$1\x3e"));z.vg&&!/<\/div>$/i.test(c)&&(c+="\x3c/div\x3e");a.outerHTML=c}};var nI=function(a){return 0==a.indexOf("+")?a.substring(1):a};var oI=function(a){a=yH(a);a.align&&(a.style.textAlign=a.align,a.removeAttribute("align"))};
var pI=function(a,b,c,d,f){var g=null;d&&(g=a.F.queryCommandValue("rtl")?"rtl":a.F.queryCommandValue("ltr")?"ltr":null);b=nI(b);var h,k;if(z.B){var m=b;k=[];d=null;var n=a.ze();h=pH(a);if(m in qI){var t=n&&n.Ob();if(t){for(var x=z.Me(window.document,"BLOCKQUOTE",null,t),J,K=0;K<x.length;K++)if(n.containsNode(x[K])){J=x[K];break}if(t=J||z.uf(t,"BLOCKQUOTE"))d=h.B("DIV",{style:"height:0"}),t.appendChild(d),k.push(d),J?n=z.bu(J,0,d,0):n.containsNode(d)&&(n=rH(n.Z(),n.va(),d,0)),n.select()}}J=a.F;!J.oc()&&
!d&&m in rI&&(J=J.m(),n&&n.isCollapsed()&&!z.hf(J)&&(d=n.Ae(0).ce(),n=d.duplicate(),n.moveToElementText(J),n.collapse(!1),n.isEqual(d)&&(n=h.createTextNode(" "),J.appendChild(n),d.move("character",1),d.move("character",-1),d.select(),k.push(n))),d=h.B("DIV",{style:"height:0"}),J.appendChild(d),k.push(d));h=k[0];k=k[1]}if(z.C){h=b;var M;sI[h]&&(M=pH(a).B("DIV",{style:"height: 0"},"x"),a.F.m().appendChild(M));!z.D(534)&&tI[h]&&(h=a.F.m(),M=pH(a).B("DIV",{style:"height: 0"},"x"),h.insertBefore(M,h.firstChild));
h=M}z.A&&(M=b,z.D("1.9")&&"formatblock"==M.toLowerCase()&&(M=a.ze(),J=M.Z(),M.isCollapsed()&&J&&"BODY"==J.tagName&&(d=M.va(),(J=J.childNodes[d])&&"BR"==J.tagName&&(M=M.ce(),M.setStart(J,0),M.setEnd(J,0)))));z.iF&&"fontsize"==b.toLowerCase()&&uI(a);M=jI(a);f&&z.ZE&&(M.execCommand("styleWithCSS",!1,!0),z.vg&&vI(a));M.execCommand(b,!1,c);f&&z.ZE&&M.execCommand("styleWithCSS",!1,!1);z.C&&!z.D("526")&&"formatblock"==b.toLowerCase()&&c&&/^[<]?h\d[>]?$/i.test(c)&&wI(a);/insert(un)?orderedlist/i.test(b)&&
(z.C&&!z.D(534)&&xI(a),z.B&&(yI(a),k&&z.O(k)));h&&z.O(h);g&&a.F.execCommand(g)};
var zI=function(a,b,c,d){var f=null,g=[],h=b&&b.Ob();if(h&&"IMG"==h.tagName||!b)return null;if(b.isCollapsed())b=b.Ae(0).ce(),z.SE?(f=pH(a).createElement("A"),b.insertNode(f)):z.RE&&(b.pasteHTML("\x3ca id\x3d'newLink'\x3e\x3c/a\x3e"),f=pH(a).m("newLink"),f.removeAttribute("id"));else{var k=z.hp();pI(a,"CreateLink",k);z.w(a.F.m().getElementsByTagName("A"),function(a){z.op(a.href,k)&&g.push(a)});g.length&&(f=g.pop());a=function(a){return gI(z.Go(a))};if(g.length&&z.Yn(g,a)){for(a=0;b=g[a];a++)fI(b,
d);g=null}}return eI(f,c,d,g)};var uI=function(a){var b=IH(z.Oz(a.F),a.F.m());z.Qd(z.Wo(b,function(a,d,f){return 1==f.Sb&&b.containsNode(a)}),function(a){z.sg(a,"font-size","");z.A&&0==a.style.length&&null!=a.getAttribute("style")&&a.removeAttribute("style")})};var wI=function(a){z.Qd(a.ze(),function(a){"Apple-style-span"==a.className&&(a.style.fontSize="",a.style.fontWeight="")})};
var xI=function(a){var b=!1;z.Qd(a.ze(),function(a){var d=a.tagName;if("UL"==d||"OL"==d)if(b){if(d=z.Lo(a)){var f=a.ownerDocument.createRange();f.setStartAfter(d);f.setEndBefore(a);if(z.np(f.toString())&&d.nodeName==a.nodeName){for(;d.lastChild;)a.insertBefore(d.lastChild,a.firstChild);d.parentNode.removeChild(d)}}}else b=!0})};
var yI=function(a){for(a=(a=a.ze())&&a.tc();a&&"UL"!=a.tagName&&"OL"!=a.tagName;)a=a.parentNode;a&&(a=a.parentNode);if(a){var b=z.wb(a.getElementsByTagName("UL"));z.xb(b,z.wb(a.getElementsByTagName("OL")));z.w(b,function(a){var b=a.type;b&&!("UL"==a.tagName?AI:BI)[b]&&(a.type="")})}};var vI=function(a){var b=[],c=z.Oz(a.F).Ob();do b.push(c);while(c=c.parentNode);a=SH(z.Od(z.Oz(a.F)),z.Od(b));a=z.Wo(a,wH);z.Qd(a,function(a){var b=a.style.outline;a.style.outline="0px solid red";a.style.outline=b})};
var CI=function(a){var b=null;z.Qd(a,function(a,d,f){if(-1!=f.Sb){a=yH(a).tagName;b=b||a;if(b!=a)throw b=null,z.Pd;f.Gp()}});return b};var DI=function(a,b){var c=b.replace("+justify","").toLowerCase();"full"==c&&(c="justify");var d=a.F.Pb.Bidi;if(d)return c==d.IX();var f=a.ze();if(!f)return!1;for(var g=f.Ob(),d=z.nb(g.childNodes,function(a){return z.Au(a)&&f.containsNode(a,!0)}),d=d.length?d:[g],g=0;g<d.length;g++){var h=yH(d[g]);if(c!=EI(h))return!1}return!0};
var EI=function(a){var b=z.yg(a,"textAlign"),b=b.replace(/^-(moz|webkit)-/,"");FI[b]||(b=a.align||"left");return b};var GI=function(a,b,c,d,f){d=nI(d);if(f){var g=jI(a);g.execCommand("styleWithCSS",!1,!0)}a=b?c.queryCommandState(d):c.queryCommandValue(d);f&&g.execCommand("styleWithCSS",!1,!1);return a};
var HI=function(a,b){z.yc.call(this);this.rt=[];for(this.mt=[];a&&"BODY"!=a.nodeName&&a!=b;){for(var c=0,d=a.previousSibling;d;)d=d.previousSibling,++c;this.rt.unshift(c);this.mt.unshift(a.nodeName);a=a.parentNode}};var II=function(a,b){for(var c,d=b,f=0;c=a.mt[f];++f)if(d=d.childNodes[a.rt[f]],!d||d.nodeName!=c)return null;return d};var JI=function(){z.nz.call(this)};
var KI=function(a,b){for(var c=z.Oz(a.F),d=c.tc(),f=a.F.m(),g;d&&d!=f;){var h=d.nodeName,k;(k="DIV"==h)||!(k=LI[h])||(k=!b)||(k=d,k=!(z.Bu(k)&&1==k.getElementsByTagName("BR").length));if(k){if(z.vg&&g){"DIV"==h&&g==d.lastChild&&z.Bu(g)&&(z.cf(g,d),z.tu(g).select());break}return}z.vg&&b&&"P"==h&&"DIV"!=h&&(g=d);d=d.parentNode}if(z.B&&!z.D(9)){var m=!1,c=c.ce(),d=c.duplicate();d.moveEnd("character",1);d.text.length&&(m=d.parentElement(),d=d.duplicate(),d.collapse(!1),d=d.parentElement(),m=m!=d&&d!=
c.parentElement())&&(c.move("character",-1),c.select())}a.F.eb.ua().execCommand("FormatBlock",!1,"\x3cDIV\x3e");m&&(c.move("character",1),c.select())};
var MI=function(a){if(z.SE){if((a=z.Oz(a.F))&&!a.isCollapsed()){var b=!0;if(z.vg){var c=a.Z(),d=a.va();c==a.la()&&c.lastChild&&"BR"==c.lastChild.tagName&&d==c.childNodes.length-1&&(b=!1)}if(b){var f=a;if(f&&!f.isCollapsed()){var g=!0,b=f.Ob(),c=new HI(f.Z(),b),d=f.va(),h;h=f;var k=h.Z();wH(k)&&(k=k.childNodes[h.va()]||k);var k=yH(k),m=h.la();wH(m)&&(m=m.childNodes[h.Ja()]||m);m=yH(m);h=k==m;if(k=!h)a:{var m=f,k=m.la(),m=m.Ja(),n=k;if(wH(n)){var t=n.childNodes[m];if(!t||1==t.nodeType&&wH(t)){k=!1;
break a}}for(t=yH(n);t!=n;){if(OH(n)){k=!0;break a}n=n.parentNode}k=m!=z.Du(k)}f.Zc();(f=II(c,b))?f=z.uu(f,d):(f=z.uu(b,b.childNodes.length),g=!1);f.select();h&&(h=yH(f.Z()),z.Bu(h,!0)&&(g="\x26nbsp;",z.vg&&"LI"==h.tagName&&(g="\x3cbr\x3e"),z.Eu(h,g),z.Gu(h.firstChild),g=!1));k&&(f=yH(f.Z()),h=OH(f),f&&h&&(z.$e(f,h.childNodes),z.O(h)));g&&(f=z.uu(II(c,b),d),f.select())}}}a=uH(a,!0)}else a=pH(a).ua(),b=a.selection.createRange(),c=z.hp(),b.pasteHTML('\x3cspan id\x3d"'+c+'"\x3e\x3c/span\x3e'),a=a.getElementById(c),
a.id="";return a};var NI=function(){};var OI=function(a){z.F.call(this);this.Qu=a||window;this.dz=z.E(this.Qu,"resize",this.$x,!1,this);this.vc=z.Pe(this.Qu)};
var PI=function(a,b){z.F.call(this);this.da=z.H(a);this.T=new z.yd(this);this.LB=new OI(this.da.Ta());this.sd={};this.Dd=this.da.B("DIV",{className:QI});z.P(this.Dd,!1);a.appendChild(this.Dd);z.sg(this.Dd,"zIndex",b);this.bn=this.Dd;this.qD=this.da.B("DIV",{className:"tr_bubble_closebox",innerHTML:"\x26nbsp;"});this.bn.appendChild(this.qD);JH(this.Dd,this.T);this.jg=new z.Jn(this.Dd)};var RI=function(a,b){return z.Gb(a.sd,function(a){return a.type==b})};
var SI=function(a,b,c,d){var f=null,g;for(g in a.sd){var h=a.sd[g].gB;if(!f||z.mf(h,f))f=a.sd[g].gB}return z.Es(f,b,a.Dd,c,null,TI,d,null,a.oO())};var UI=function(a,b,c,d,f,g){this.type=c;this.gB=f;this.BT=g;this.element=a.B("DIV",{className:"tr_bubble_panel",id:b},a.B("DIV",{className:"tr_bubble_panel_title"},d?d+":":""),a.B("DIV",{className:"tr_bubble_panel_content"}))};var VI=function(){z.nz.call(this);this.ec=new z.yd(this);this.EM=null};var WI=function(a,b){return new PI(a,b)};
var XI=function(a){var b=a.vX||a.F.Mk.document.body;a.da=z.H(b);var c=YI[a.F.id];c||(c=(a.EM||WI).call(null,b,a.F.xM||0),YI[a.F.id]=c);return c};var ZI=function(a){if(a.mi){var b=XI(a),c=a.mi;z.O(b.sd[c].element);delete b.sd[c];c=z.Xn(b.sd);1>=c&&z.ij(b.Dd,"tr_multi_bubble");0==c?b.rD():b.ha();a.yF()}};var $I=function(a){return a?z.Qo("//www.zhihu.com/equation","tex",a):""};var aJ=function(){VI.call(this)};var bJ=function(a){this.RN=a};var cJ=function(a){z.Mc.call(this,"change");this.isValid=a};
var dJ=function(a){z.Q.call(this,a)};var eJ=function(a,b,c,d,f,g,h,k){this.Vb=b;this.Om=h||[];b=k||fJ.ba();k=[];c=-c;d=-d;for(var m=0;m<h.length;m++)k.push(a.K().B("DIV",{"class":b.U()+"-item",style:"width:"+f+"px;height:"+g+"px;background-position:"+c+"px "+d+"px;"})),c-=f;this.hg=a;z.uD.call(this,k,b,a.K())};var gJ=function(a,b,c){z.Mc.call(this,a,c);this.nT=b};var fJ=function(){};var hJ=function(a,b,c){z.Q.call(this,c);this.Cj=b;this.hg=a.mT};
var iJ=function(a){var b=a.ul();if(b!=a.HG){a.HG=b;var c=!(1024<b.length);a.dispatchEvent(new cJ(c));a=a.GT;var d=z.H(a);d.hp(a);b&&(c?(b=$I(b),b=d.B("IMG",{src:b})):(b=z.u("Equation is too long"),b=d.B("DIV",{"class":"ee-warning"},b)),d.appendChild(a,b))}};var jJ=function(a,b,c){z.Q.call(this,c);this.ED=a;this.Cj=b};var kJ=function(a,b,c,d){UH.call(this,b);this.lj=new jJ(a,d,b);this.lj.render();this.lj.EA(c);this.lj.addEventListener("+equation",this.Dz,!1,this)};
var lJ=function(a){eJ.call(this,a,"a",0,150,18,18,"\\leftarrow \\rightarrow \\leftrightarrow \\Leftarrow \\Rightarrow \\Leftrightarrow \\uparrow \\downarrow \\updownarrow \\Uparrow \\Downarrow \\Updownarrow".split(" "));z.wD(this,new z.Ie(12,1))};var mJ=function(a){eJ.call(this,a,"c",0,70,18,18,"\\leq \\geq \\prec \\succ \\preceq \\succeq \\ll \\gg \\equiv \\sim \\simeq \\asymp \\approx \\ne \\subset \\supset \\subseteq \\supseteq \\in \\ni \\notin".split(" "));z.wD(this,new z.Ie(7,3))};
var nJ=function(a){eJ.call(this,a,"g",0,30,18,18,"\\alpha \\beta \\gamma \\delta \\epsilon \\varepsilon \\zeta \\eta \\theta \\vartheta \\iota \\kappa \\lambda \\mu \\nu \\xi \\pi \\varpi \\rho \\varrho \\sigma \\varsigma \\tau \\upsilon \\phi \\varphi \\chi \\psi \\omega \\Gamma \\Delta \\Theta \\Lambda \\Xi \\Pi \\Sigma \\Upsilon \\Phi \\Psi \\Omega".split(" "));z.wD(this,new z.Ie(7,6))};
var oJ=function(a){eJ.call(this,a,"m",0,90,30,56,"x_{a};x^{b};x_{a}^{b};\\bar{x};\\tilde{x};\\frac{a}{b};\\sqrt{x};\\sqrt[n]{x};\\bigcap_{a}^{b};\\bigcup_{a}^{b};\\prod_{a}^{b};\\coprod_{a}^{b};\\left( x \\right);\\left[ x \\right];\\left\\{ x \\right\\};\\left| x \\right|;\\int_{a}^{b};\\oint_{a}^{b};\\sum_{a}^{b}{x};\\lim_{a \\rightarrow b}{x}".split(";"));z.wD(this,new z.Ie(10,2))};var pJ=function(a){eJ.call(this,a,"mn",0,0,46,18,["g","s","c","m","a"],qJ.ba());z.wD(this,new z.Ie(5,1))};
var qJ=function(){};var rJ=function(a){eJ.call(this,a,"s",0,50,18,18,"\\times \\div \\cdot \\pm \\mp \\ast \\star \\circ \\bullet \\oplus \\ominus \\oslash \\otimes \\odot \\dagger \\ddagger \\vee \\wedge \\cap \\cup \\aleph \\Re \\Im \\top \\bot \\infty \\partial \\forall \\exists \\neg \\angle \\triangle \\diamond".split(" "));z.wD(this,new z.Ie(7,5))};var sJ=function(a){z.F.call(this);this.DN=a;this.dI={};this.Pm=null;this.T=new z.yd(this);this.Gw=new z.ud(300);this.T.g(this.Gw,"tick",this.nF)};
var tJ=function(a){this.Cj=a||"";$H.call(this,"+equation")};var uJ=function(){z.nz.call(this)};var vJ=function(){z.nz.call(this)};var wJ=function(a,b){var c=z.Oz(a.F);return z.uf(c.Ob(),"LI")||TH(c,function(a){return"LI"==a.tagName})?(a.F.execCommand(b.shiftKey?"+outdent":"+indent"),b.preventDefault(),!0):!1};var xJ=function(a){z.nz.call(this);this.sR=a};var yJ=function(a){z.F.call(this);this.lM=a};var zJ=function(){z.F.call(this);this.oR=100;this.Sd=[];this.lk=[];this.Dt=[]};
var AJ=function(a,b,c){if(b.length){var d=b.pop();c.push(d);a.Dt.push({type:b==a.Sd?"before_undo":"before_redo",UE:b==a.Sd?d.xB:d.kA,state:d});1==a.Dt.length&&a.Fg();0!=b.length&&1!=c.length||a.dispatchEvent("state_change")}};var BJ=function(a){z.nz.call(this);a=a||new zJ;this.WG&&z.od(this.WG);this.Ef=a;this.WG=z.E(this.Ef,"state_change",this.zN,!1,this);this.mj={};this.xn={};this.cG=null;this.AM=(0,z.q)(this.jU,this)};
var CJ=function(a,b){var c=b.Qg,d,f;b.queryCommandValue("usinglorem")?(d="",f=null):(d=b.m().innerHTML,f=new DJ(b),f=f.isValid()?f:null);var g=a.xn[c];if(g){if(g.Ei==d)return;if(""==d||""==g.Ei){var h;h=b.Rt(8,"",{});if(d==h&&""==g.Ei||g.Ei==h&&""==d)return}g.lA=d;g.QT=f;h=a.Ef;if(0==h.Sd.length||!g.equals(h.Sd[h.Sd.length-1])){h.Sd.push(g);h.Sd.length>h.oR&&h.Sd.shift();var k=h.lk.length;h.lk.length=0;h.dispatchEvent({type:"state_added",state:g});(1==h.Sd.length||k)&&h.dispatchEvent("state_change")}}a.xn[c]=
new EJ(c,d,f,a.AM)};var EJ=function(a,b,c,d){yJ.call(this,!0);this.Fn=a;this.MI=d;this.Ei=b;this.TJ=c};
var DJ=function(a){this.$d=a;var b=a.eb.Ta();a=(a=z.Oz(a))&&a.$f()&&a.Ta()==b?a:null;if(z.SE){if(b=a,this.Is=!1,b){var c=z.zt(b),d=z.Bt(b);if(c&&d){a=z.At(b);var c=new HI(c,this.$d.m()),f=z.Ct(b),d=new HI(d,this.$d.m());b.Wg()?(this.Ca=d,this.WA=f,this.Ba=c,this.Yw=a):(this.Ca=c,this.WA=a,this.Ba=d,this.Yw=f);this.Is=!0}}}else z.RE&&(b=a,this.Is=!1,b&&(a=b.Ae(0).ce(),z.mf(this.$d.m(),a.parentElement())&&(b=this.$d.eb.ua().body.createTextRange(),b.moveToElementText(this.$d.m()),d=a.duplicate(),d.collapse(!0),
d.setEndPoint("StartToStart",b),this.Ca=FJ(d),a=a.duplicate(),a.setEndPoint("StartToStart",b),this.Ba=FJ(a),this.Is=!0)))};var FJ=function(a){var b=a.duplicate(),c=a.text,d=c.length;b.collapse(!0);b.moveEnd("character",d);for(var f,g=10;(f=b.compareEndPoints("EndToEnd",a))&&(d-=f,b.moveEnd("character",-f),--g,0!=g););a=0;for(b=c.indexOf("\n\r");-1!=b;)++a,b=c.indexOf("\n\r",b+1);return d+a};
var GJ=function(a,b){z.F.call(this);this.ga=new z.yd(this);this.$d=a;this.Eb=b;this.gA=[];z.ch(this.Eb,function(a){a.hb&&this.gA.push(HJ(a.de()))},this);this.Eb.Ne(!1);this.ga.g(this.$d,"cvc",this.XV).g(this.Eb,"action",this.sO)};var HJ=function(a){return a};var IJ=function(a,b){z.hy.call(this,a||z.AD.ba(),b)};var JJ=function(a){z.nz.call(this);this.BB=z.sm.Lu+"/upload";z.Nb(this.J={},this.defaults,a||{})};
var KJ=function(a){var b=pH(a),c=(0,window.$)('\x3cdiv class\x3d"editable-dropzone"\x3e\x3cdiv class\x3d"row"\x3e\x3cdiv class\x3d"cell"\x3e\x3cdiv\x3e拖拽至此处上传\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e');b.Hy(c[0],a.F.m());return c};var LJ=function(a){var b=pH(a),c=b.B("IMG",{"class":"",style:"display:block",src:z.sm.YA+"/img/spinner2.gif"}),d=z.Oz(a.F);d&&HH(d)&&z.mf(a.F.m(),d.Ob())?d.kg(c):z.Bu(a.F.Ea)?z.df(a.F.m(),c,0):a.F.m().appendChild(c);z.B||(z.Hu(c,!1),b.Ta().focus());z.Qz(a.F);return(0,window.$)(c)};
var MJ=function(a,b){var c=[{display:"none"},{display:"table",width:a.VB.width(),height:a.VB.height(),"background-color":"rgba(255, 255, 255, 0.5)"}];c[2]=window.$.extend({},c[1],{"background-color":"rgba(245, 245, 245, 0.5)"});a.GK.css(c[b])};
var NJ=function(a,b){var c=new window.FormData;c.append("via","xhr2");c.append("upload_file",b);var d;d=window.$.ajaxSettings.xhr();d.withCredentials=!0;var f=window.$.ajax({url:a.BB,data:c,processData:!1,contentType:!1,xhr:function(){return d},type:"POST"}).done(function(a){"string"===window.$.type(a)&&(a=JSON.parse(a));if(1===a.code)z.W.message(a.msg);else{var b=new window.Image;b.src=a.msg[0];b.setAttribute("originImgSrc",b.src.replace("_m.jpg","_r.jpg"));b.setAttribute("data-rawWidth",a.msg[1]);
b.setAttribute("data-rawHeight",a.msg[2]);f.eC.after(b)}}).fail(function(){z.W.message("上传失败！\x3e_\x3c")}).always(function(){f.eC.remove()});f.eC=LJ(a)};var OJ=function(){z.nz.call(this)};var PJ=function(a){return a&&"BR"===a.tagName};
var QJ=function(a,b){function c(a,b){return{KA:a,qH:b}}z.C&&(a.normalize(),b=z.qu());var d=RJ(b);if(!d)return c(!1,null);if(z.Bu(a))return c(!0,a);for(var f=d;f!==a;){if(OH(f))return c(!1,null);f=f.parentNode}if(PJ(d)&&PJ(d.previousSibling))return c(!0,d);d=b.Ob();return!d||1!==d.nodeType||d.childNodes.length&&!z.Bu(d)?c(!1,null):c(!0,d)};var RJ=function(a){var b=a.la(),c=a.Ja();a=a.tc();var d=a.childNodes.length;3!==b.nodeType&&d&&(b=a.childNodes[c===d?d-1:c]);return b};
var SJ=function(a){z.Q.call(this);z.Nb(this.J={},this.defaults,a||{});this.le=null};var TJ=function(a){var b=z.ha(a);a=b.next().value;b=b.next().value;return{label:a,value:b,toString:z.jb(a)}};var UJ=function(a){var b=z.rb(VJ,function(b){var d=z.ha(b);b=d.next().value;d=d.next().value;return b===a||d===a});return b&&TJ(b)};
var WJ=function(a,b,c){var d=a.J,f={},g=new z.es(XJ,!1),h=new z.Is(c,f);c=new z.vs(null,null,!1);g.pi=function(a){return function(b,c,d){(0,z.cb)(b)?a.apply(this,arguments):d(b,XJ)}}(g.pi);f.td=function(b,c,f){b=b.data;b.value===a.le&&(z.V.add(f,d.nD),f.appendChild(z.N("i","icon "+d.nD)));f.appendChild(window.document.createTextNode(b.toString()))};f=new z.hs(g,h,c);c.aa=f;c.Nk(b);return f};
var YJ=function(a,b,c){var d=a.J,f=a.v(),g=WJ(a,b,c);g.Tl=20;f.g(g,"suggestionsupdate",function(){g.Yf(g.Uc+0)}).g(g,"update",function(a){this.Jz(a.ri)}).g(g,"dismiss",function(){this.wi(!0)});b=g.M;b.className=d.YQ;b.jh=d.hT;b.vv=d.yg;a.aa=g};var ZJ=function(a){z.nz.call(this);z.Nb(this.J={},this.defaults,a||{});this.ex=this.Eb=null};var $J=function(a){return"P"===a.tagName};var aK=function(a){return 3===a.nodeType};var bK=function(a){return a&&"PRE"===a.tagName};
var cK=function(a){var b,c=new z.dx(bK,!1,null,a),d=z.N("div",{style:"display:none"});z.Pw(c,new z.qg(4,0,0,0));z.bx(c,new z.qg(4,0,0,0));c.Ep=150;c.$n=100;c.mh(d);c.className="hc-lang-select";z.E(c,"beforeshow",function(a){b=a.target.anchor;c.setPosition(new z.Mw(b,1));if(b.lang){a=f;var d=UJ(b.lang);d&&a.Da(d.value);f.wi(!0)}else f.pk("选择语言")});z.E(c,"beforehide",function(c){b=null;f.Da(null);if((c=c.target)&&a.contains(c)&&bK(c))return!1});var f=new SJ;f.render(d);z.E(f,"change",function(a){b&&
(b.lang=a.gT.value,c.G(!1))});return{Fx:z.jb(c),GX:z.jb(f),H:function(){c.H();f.H()}}};
var dK=function(a){function b(a){return z.y(f,a)}function c(){var a=window.document.createTextNode("\n");f.push(a);return a}var d=window.document.createElement("div");d.innerHTML=a;var f=[],g=z.cp(b);a=z.Ho(d,MH);z.w(a,function(a){a.lastChild&&"BR"===a.lastChild.tagName&&a.removeChild(a.lastChild);a.firstChild||a.appendChild(window.document.createTextNode(""));a.insertBefore(c(),a.firstChild);a.appendChild(c())});a=z.wb(d.getElementsByTagName("br"));z.w(a,function(a){a!==a.parentNode.lastChild&&z.No(window.document.createTextNode("\n"),
a)});d=z.Ho(d,aK);d=z.fp(function(a){return z.nb(a,function(c,d){var f=a[d-1];return!f||!(b(f)&&b(c))})},function(a){var b=z.ap(a,g);return-1!==b?a.slice(0,b+1):a},function(a){var b=z.sb(a,g);return-1!==b?a.slice(b):a})(d);return z.ob(d,function(a){return a.nodeValue}).join("").replace(/\xa0/g," ")};var eK=function(a,b){a.Eb&&a.ex&&z.ch(a.Eb,function(a){a instanceof z.DD&&a.Ua(!b||z.y(this.ex,a.de()))},a)};var fK=function(a,b,c){for(a=a.F.Ea;b!==a;){if(c(b))return b;b=b.parentNode}};
var gK=function(a){var b,c=z.qu();c&&a.F.Ea.contains(c.Ob())?(b=c.Z(),a=(b=fK(a,b,bK))?"1":"2"):a="0";return{state:a,Qt:c,code:b}};var hK=function(a,b){var c=window.document.createTextNode(b);a.kg(c);z.Hu(c)};var iK=function(a,b,c){a.qn("i",function(a,f){b.kg(a);a=f();c=z.Ma(c);z.No(window.document.createTextNode(c),a)})};var jK=function(a,b){for(var c=a,d=[];c&&c!==b;)d.push([c.parentNode.childNodes.length,z.mb(c.parentNode.childNodes,c)]),c=c.parentNode;return d};
var kK=function(a){var b=gK(a);a=b.Qt;var c=b.code;if("1"===b.state){var b=function(a,b){return b===a.length||lK&&b===a.length-1&&"\n"===a.slice(-1)},d=a.la(),f=jK(d,c),f=!f.length||z.Yn(f,function(a){return a[0]===a[1]+1}),g=aK(d);f&&(!g||g&&b(d.nodeValue,a.Ja()))&&mK(c)}};var mK=function(a){OH(a)||z.cf(window.document.createElement("br"),a)};var nK=function(a,b){a.qn("i",function(a,d){b.kg(a);(0,window.setTimeout)(function(){var b=window.document.createTextNode("\r");a=d();z.No(b,a);z.Hu(b)})})};
var oK=function(a,b,c){var d=a.J,f;b.Zc();var g=pK(a,b);g?(f=window.document.createElement("PRE"),g.parentNode.insertBefore(f,g)):a.qn("PRE",function(a,c){b.insertNode(a);f=c()});!c&&z.B&&(c=" ");f.lang=d.qN;z.nf(f,c);z.Bu(f)?z.Gu(f.firstChild):z.Hu(f.lastChild);mK(f)};
var pK=function(a,b){function c(a){return a.parentNode.insertBefore(window.document.createTextNode(""),a)}var d=uH(b,!0),f=d.node,g,h=a.F.Ea,k=fK(a,f,z.dp(MH,z.cp($J)))||h;if(aK(f)){var m=f.parentNode;!f.nodeValue&&m!==h&&z.Bu(m)?(g=c(m),f=c(g),m.parentNode.removeChild(m)):g=z.B&&d.offset===f.length?z.cf(window.document.createTextNode(""),f):f.splitText(d.offset)}else"BR"===f.tagName&&(g=f,f=c(f));return g?(d=LH(f,g,k),f=d.firstChild,z.$e(k,d.childNodes),f):null};
var qK=function(){z.nz.call(this);this.eT=null};var rK=function(a){a.push("\x3cbr\x3e")};var sK=function(a){if(!z.Oz(a.F).isCollapsed()){var b=a.eT||(0,z.q)(a.DI,a);tK(a,b);pH(a).ua().execCommand("RemoveFormat",!1,void 0);z.cF&&tK(a,function(a){var b=z.D("528")?/&nbsp;/g:/\u00A0/g;return a.replace(b," ")})}};var uK=function(a,b){for(var c=a.F.m();b&&b!=c;){if("TABLE"==b.tagName)return b;b=b.parentNode}return null};
var tK=function(a,b){var c=z.Oz(a.F);if(!(1<c.wj())){if(z.A||z.Hc){var d=IH(c,a.F.m()),f=uK(a,d.Z()),g=uK(a,d.la());if(f||g){if(f==g)return;var h,k=c;h=f;var c=g,d=new CH(k),m=k.Z(),n=k.va(),t=k.la(),k=k.Ja(),x=pH(a);if(h){var J=x.createTextNode("");z.cf(J,h);m=J;n=0}c&&(J=x.createTextNode(""),z.bf(J,c),t=J,k=0);z.bu(m,n,t,k).select();h=d;f||(c=z.O(kH(h,!0)),a.VA=c);g||(c=z.O(kH(h,!1)),a.Xw=c);c=z.Oz(a.F);d=IH(c,a.F.m())}d.select();c=d}m=c;c=pH(a).B("DIV");d=m.ce();z.SE?c.appendChild(d.cloneContents()):
z.RE&&(n=m.Jd(),n=n.replace(/\r\n/g,"\r"),t=n.length,m=t-z.jp(n).length,n=t-z.ip(n).length,d.moveStart("character",m),d.moveEnd("character",-n),m=d.htmlText,"Formatted"==d.queryCommandValue("formatBlock")&&(m=z.Na(d.htmlText)),c.innerHTML=m);m=b(c.innerHTML);x=z.Oz(a.F);c=pH(a);n=z.hp();d=z.hp();m='\x3cspan id\x3d"'+n+'"\x3e\x3c/span\x3e'+m+'\x3cspan id\x3d"'+d+'"\x3e\x3c/span\x3e';k=z.hp();t='\x3cspan id\x3d"'+k+'"\x3e\x3c/span\x3e';if(z.RE){J=x.Ae(0).ce();J.pasteHTML(t);for(var K;(K=J.parentElement())&&
z.Bu(K)&&!BH(K);){x=K.nodeName;if("TD"==x||"TR"==x||"TH"==x)break;z.O(K)}J.pasteHTML(m);(k=c.m(k))&&z.O(k)}else if(z.SE){c.ua().execCommand("insertImage",!1,k);x=new RegExp("\x3c[^\x3c]*"+k+"[^\x3e]*\x3e");K=z.Oz(a.F).Ob();3==K.nodeType&&(K=K.parentNode);for(;!x.test(K.innerHTML);)K=K.parentNode;if(z.A)z.Eu(K,K.innerHTML.replace(x,m));else{z.Eu(K,K.innerHTML.replace(x,t));for(K=k=c.m(k);(K=k.parentNode)&&z.Bu(K)&&!BH(K);){x=K.nodeName;if("TD"==x||"TR"==x||"TH"==x)break;z.cf(k,K);z.O(K)}z.Eu(K,K.innerHTML.replace(new RegExp(t,
"i"),m))}}K=c.m(n);c=c.m(d);z.bu(K,0,c,c.childNodes.length).select();z.O(K);z.O(c);(z.A||z.Hc)&&h&&(c=z.Oz(a.F),K=a.F.m(),a.VA&&(K.insertBefore(a.VA,K.firstChild),a.VA=null),a.Xw&&(K.appendChild(a.Xw),a.Xw=null),K=null,d=kH(h,!0),m=kH(h,!1),d&&m&&(K=z.bu(d,0,m,0)),f=f?K:c,g=g?K:c,rH(f.Z(),f.va(),g.la(),g.Ja()).select(),h.H())}};var vK=function(){qK.call(this)};var wK=function(a){UH.call(this,a);this.T=new z.yd(this);this.BB=z.sm.Lu+"/upload";this.IM=!z.B};
var xK=function(a){z.Mc.call(this,"ok");var b=a[0];this.Ll=b;this.aI=b.replace("_m.jpg","_r.jpg");this.xI=a[1];this.wI=a[2]};var yK=function(a,b){function c(a){a.eq(b).addClass("selected").siblings().removeClass("selected")}var d=(0,window.$)(".tab-nav",a.eB),f=(0,window.$)(".tab-content",a.form);z.P(a.df,!1);var g=f.eq(b);g.find("input").val("");c(d);c(f);g.find(":text").focus()};var zK=function(a,b){z.P(a.ah,!1);a.df.innerHTML=b;z.P(a.df,!0)};var AK=function(){$H.call(this,"image");this.T=new z.yd(this)};
var BK=function(a){UH.call(this,a);this.T=new z.yd(this)};var CK=function(a,b,c,d,f){z.Mc.call(this,"ok");this.fW=a;this.eW=b;this.jK=f;this.eV=c;this.poster=d};var DK=function(a,b){b=z.qr(b);if(!b)return!1;var c=b.match(/[\-a-zA-Z0-9@:%_\+.~#?&\/\/=]{2,256}\.[a-z]{2,4}\b(\/[\-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)?/gi);c||(z.P(a.ah,!1),a.df.innerHTML="我们无法识别你输入的视频页地址",z.P(a.df,!0));return c};var EK=function(){$H.call(this,FK);this.T=new z.yd(this)};var GK=function(){};
var HK=function(a,b){var c=[];b.enableFullScreen&&c.push("toggleFullScreen");c.push("+bold","+italic","+underline",new IJ,"+blockquote","+code","+insertOrderedList","+insertUnorderedList","+equation");b.canUploadMedia_&&c.push(new IJ,"image",FK);b.useRemoveFormat_&&c.push(new IJ,"+removeFormat");for(var d=z.H(a),f=[],g=0,h;h=c[g];g++){if(z.pa(h)){var k=void 0;if(h=z.tG[h]){var k=h.factory||z.iE,m=h.Aa,n=h.S,t=h.caption,x=h.Na,J=d||z.H(),k=k(m,n,t,x,null,J);h.hb&&(k.hb=!0)}h=k}h&&f.push(h)}c=z.H(a);
c=new AH(z.BD.ba(),z.KE,c);d=z.Ng(a);c.oh(d);c.Ne(!1);for(g=0;h=f[g];g++)h.Rb(32,!1),h.oh(d),c.L(h,!0);c.render(a);return c};var IK=function(a,b){var c=a.m(),d=new z.kA;d.w(c);var f=z.N("div",{style:"display:none",className:"tr-spinner spinner-gray"});b.m().appendChild(f);d.on("willScrape",function(){z.P(f,!0)}).on("didScrape",function(){z.P(f,!1)});z.Bc(a,d)};z.Et.prototype.sh=z.Y(53,function(a,b){this.insertNode(a,!0);this.insertNode(b,!1)});
z.Jt.prototype.sh=z.Y(52,function(a,b){var c=z.Se(z.Ke(this.Z()));if(c=z.qu(c))var d=c.Z(),f=c.la(),g=c.va(),h=c.Ja();var k=this.O.cloneRange(),m=this.O.cloneRange();k.collapse(!1);m.collapse(!0);k.insertNode(b);m.insertNode(a);k.detach();m.detach();if(c){if(3==d.nodeType)for(;g>d.length;){g-=d.length;do d=d.nextSibling;while(d==a||d==b)}if(3==f.nodeType)for(;h>f.length;){h-=f.length;do f=f.nextSibling;while(f==a||f==b)}z.bu(d,g,f,h).select()}});
z.Ot.prototype.sh=z.Y(51,function(a,b){var c=this.O.duplicate(),d=this.O.duplicate();z.Wt(c,a,!0);z.Wt(d,b,!1);this.Ed()});z.$t.prototype.sh=z.Y(50,function(a,b){z.du(this).sh(a,b);this.Ed()});z.v(mH,z.ut);mH.prototype.gp=function(a){z.O(kH(this,!0));z.O(kH(this,!1));return a};
mH.prototype.$t=function(){var a=null,b=kH(this,!this.sA),c=kH(this,this.sA);if(b&&c){var a=b.parentNode,b=z.mb(a.childNodes,b),d=c.parentNode,c=z.mb(d.childNodes,c);d==a&&(this.sA?b--:c--);a=z.bu(a,b,d,c);a=this.gp(a);a.select()}else this.gp();return a};mH.prototype.D=function(){this.gp();this.da=null};z.Qw.prototype.Gx=z.Y(43,function(){return this.m().innerHTML});
z.Ot.prototype.$f=z.Y(41,function(){var a=this.xr.body.createTextRange();a.moveToElementText(this.xr.body);return this.Bg(new z.Ot(a,this.xr),!0)});z.$t.prototype.$f=z.Y(40,function(){return(!this.xa||lH(this.xa))&&(!this.ta||lH(this.ta))&&(!(z.B&&!(9<=z.Ug))||z.du(this).$f())});z.fu.prototype.$f=z.Y(39,function(){var a=!1;try{a=z.Yn(this.Yh(),function(a){return z.B?!!a.parentNode:z.mf(a.ownerDocument.body,a)})}catch(b){}return a});z.lu.prototype.$f=z.Y(38,function(){return z.Yn(z.yt(this),function(a){return a.$f()})});
z.Jt.prototype.Zc=z.Y(37,function(){var a=this.O;a.extractContents();if(a.startContainer.hasChildNodes()){var b=a.startContainer.childNodes[a.startOffset];if(b){var c=b.previousSibling;""==z.Go(b)&&z.O(b);c&&""==z.Go(c)&&z.O(c)}}if(z.Kl){var b=this.Z(),c=this.va(),d=this.la(),f=this.Ja(),g=b.nextSibling;b==d&&b.parentNode&&3==b.nodeType&&g&&3==g.nodeType&&(b.nodeValue+=g.nodeValue,z.O(g),a.setStart(b,c),a.setEnd(d,f))}});
z.Ot.prototype.Zc=z.Y(36,function(){if(!this.isCollapsed()&&this.O.htmlText){var a=this.Z(),b=this.la(),c=this.O.text,d=this.O.duplicate();d.moveStart("character",1);d.moveStart("character",-1);d.text==c&&(this.O=d);this.O.text="";this.Ed();c=this.Z();d=this.va();try{var f=a.nextSibling;a==b&&a.parentNode&&3==a.nodeType&&f&&3==f.nodeType&&(a.nodeValue+=f.nodeValue,z.O(f),this.O=z.Pt(c),this.O.move("character",d),this.Ed())}catch(g){}}});z.$t.prototype.Zc=z.Y(35,function(){z.du(this).Zc();this.Ed()});
z.fu.prototype.Zc=z.Y(34,function(){if(this.O){for(var a=[],b=0,c=this.O.length;b<c;b++)a.push(this.O.item(b));z.w(a,z.O);this.collapse(!1)}});z.lu.prototype.Zc=z.Y(33,function(){z.w(z.yt(this),function(a){a.Zc()})});z.wt.prototype.kg=z.Y(32,function(a){this.isCollapsed()||this.Zc();return this.insertNode(a,!0)});z.fu.prototype.kg=z.Y(31,function(a){a=this.insertNode(a,!0);this.isCollapsed()||this.Zc();return a});
z.vt.prototype.Gp=z.Y(30,function(){var a=this.Ic?-1:1;this.Sb==a&&(this.Sb=-1*a,this.depth+=this.Sb*(this.Ic?-1:1))});z.Ft.prototype.Gp=z.Y(29,function(){z.Ft.o.Gp.apply(this);if(z.mf(this.node,this.ta))throw z.Pd;});z.Qp.prototype.wi=z.Y(28,function(a,b){var c=a.qd(),d=this.U()+"-collapse-left",f=this.U()+"-collapse-right";a.jj(c?f:d,!!(b&1));a.jj(c?d:f,!!(b&2))});z.$p.prototype.wi=z.Y(27,function(a){this.M.wi(this,a)});z.Aj.prototype.Ax=z.Y(23,function(){z.Cj(this);return this.pc});
z.ad.prototype.wl=z.Y(2,function(a,b){var c=this.ic[a.toString()],d=[];if(c)for(var f=0;f<c.length;++f){var g=c[f];g.Wk==b&&d.push(g)}return d});z.F.prototype.wl=z.Y(1,function(a,b){return this.Zd.wl(String(a),b)});z.v(AH,z.Vr);AH.prototype.ee=function(a){AH.o.ee.call(this,a);this.tf||z.Zr(this)};z.v(CH,mH);CH.prototype.gp=function(a){var b=kH(this,!0),c=kH(this,!1),b=b&&c?z.Jo(b,c):b||c;CH.o.gp.call(this);if(a)return zH(b,a);b&&(a=z.qu(z.Se(z.Ke(b))),(a=zH(b,a))&&a.select())};
var KH={text:!0,file:!0,url:!0},NH={ADDRESS:!0,ARTICLE:!0,ASIDE:!0,BLOCKQUOTE:!0,BODY:!0,CAPTION:!0,CENTER:!0,COL:!0,COLGROUP:!0,DETAILS:!0,DIR:!0,DIV:!0,DL:!0,DD:!0,DT:!0,FIELDSET:!0,FIGCAPTION:!0,FIGURE:!0,FOOTER:!0,FORM:!0,H1:!0,H2:!0,H3:!0,H4:!0,H5:!0,H6:!0,HEADER:!0,HGROUP:!0,HR:!0,ISINDEX:!0,OL:!0,LI:!0,MAP:!0,MENU:!0,NAV:!0,OPTGROUP:!0,OPTION:!0,P:!0,PRE:!0,SECTION:!0,SUMMARY:!0,TABLE:!0,TBODY:!0,TD:!0,TFOOT:!0,TH:!0,THEAD:!0,TR:!0,UL:!0},FK,JK;z.v(UH,z.F);
UH.prototype.show=function(){this.af||(this.af=this.vw(),this.af.g("hide",this.vO,!1,this));this.af.G(!0)};UH.prototype.hide=function(){this.af&&this.af.G(!1)};UH.prototype.rb=function(){return!!this.af&&this.af.V()};VH.prototype.La=function(a){this.Ki.La(a);return this};VH.prototype.Cd=function(a,b,c){c=c||z.hp();this.gn.set(c,a);this.en[c]=b;return this};VH.prototype.Dh=function(a){z.gj(this.Ki.Xh(),a);return this};VH.prototype.ia=function(a){this.Ki.R().appendChild(a);return this};z.e=UH.prototype;
z.e.Ax=function(a){return this.af.qc.hf(a)};z.e.sP=function(a){return(a=this.sn(a))?this.dispatchEvent(a):!1};z.e.Tn=function(){return this.dispatchEvent("cancel")};z.e.D=function(){this.af&&(this.hide(),this.af.H(),this.af=null);UH.o.D.call(this)};z.e.vO=function(){this.dispatchEvent("afterhide")};z.v($H,z.nz);z.e=$H.prototype;z.e.Ge=function(a){return a==this.YM};z.e.execCommand=function(a,b){return this.ef.apply(this,arguments)};z.e.ZE=function(){return this.Ga};z.e.ef=function(a,b){this.RI||bI(this);this.Ga||(this.Ga=this.uw(z.H(this.F.Mk),b));var c=z.Oz(this.F);this.KI=oH(this);this.VI=c&&new CH(c);z.vu(this.F.eb.Ta());z.md(this.Ga,"afterhide",this.Sn,!1,this);this.F.Sg=!0;this.Ga.show();this.dispatchEvent("dialogOpened");z.Pz(this.F);return!0};
z.e.Sn=function(){this.F.Sg=!1;aI(this);this.KI();this.RI||bI(this);this.dispatchEvent("dialogClosed");z.Pz(this.F);this.F.qr.selectionchange=(0,z.G)()};z.e.D=function(){bI(this);$H.o.D.call(this)};z.e.RI=!1;z.e.Ly=!1;var hI=/^[\w-]+(\.[\w-]+)*\@([\w-]+\.)+(\d+|\w\w+)$/i;z.v(iI,z.nz);iI.prototype.ld=function(){return"BTF"};var KK={SW:"+link",zW:"+createLink",IW:"+formatBlock",MW:"+indent",ZW:"+outdent",fX:"+strikeThrough",KW:"+insertHorizontalRule",gX:"+subscript",hX:"+superscript",kX:"+underline",vW:"+bold",NW:"+italic",HW:"+fontSize",GW:"+fontName",FW:"+foreColor",pW:"+backColor",YW:"+insertOrderedList",oX:"+insertUnorderedList",OW:"+justifyCenter",PW:"+justifyFull",RW:"+justifyRight",QW:"+justifyLeft"},LK=z.Yo(KK);iI.prototype.Ge=function(a){return a in LK};
var MK=["+createLink"];z.e=iI.prototype;z.e.xG=function(a){return z.y(MK,a)};z.e.ze=function(){return z.Oz(this.F)};
z.e.ef=function(a,b,c,d){var f,g,h,k,m,n=b;switch(a){case "+backColor":if(null!==n)if(z.$E){a=n;g=z.Oz(this.F);var t,x;g&&g.isCollapsed()&&(t=pH(this).createTextNode(z.A?" ":""),h=g.Z(),x=1==h.nodeType?h:h.parentNode,""==x.innerHTML?(x.style.textIndent="-10000px",x.appendChild(t)):(x=pH(this).B("SPAN",{style:"text-indent:-10000px"},t),g.kg(x)),z.tu(t).select());pI(this,"hiliteColor",a,!1,!0);t&&(z.A&&(t.data=""),x.style.textIndent="")}else z.vg?pI(this,"hiliteColor",n):pI(this,a,n);break;case "+createLink":m=
zI(this,b,c,d);break;case "+link":a:{m=n;this.F.rf||pH(this).Ta().focus();g=(a=this.ze())&&a.Ob();if((g=z.uf(g,"A"))&&z.vf(g,BH))z.ef(g);else if(m=zI(this,a,"/",m)){if(!this.F.execCommand("link",m))if(h=this.F.Mk.prompt(z.FF,"http://"))a=dI(m)||h,g=m.qe,g.href=h,n=dI(m),a!=n&&(h=z.yu(g),h.tagName&&"IMG"==h.tagName?h.setAttribute("alt",a?a:""):(3==h.nodeType&&(h=h.parentNode),z.Go(h)!=n&&(h=g),z.af(h),g=z.H(h),h.appendChild(g.createTextNode(a))),m.Fw=null),a=m.qe,z.dF?(g=a.nextSibling,g&&3==g.nodeType&&
(z.Ka(g.data," ")||z.Ka(g.data," "))||(g=z.H(a).createTextNode(" "),z.cf(g,a)),z.uu(g,1).select()):z.Hu(a,!1);else{a=z.tu(m.qe);a=new CH(a);z.ef(m.qe);for(m.qe=null;m.ix.length;)z.ef(m.ix.pop());a.restore().select();m=null;break a}break a}m=null}break;case "+justifyCenter":case "+justifyFull":case "+justifyRight":case "+justifyLeft":pI(this,a,null,!1,!0);z.A&&pI(this,a,null,!1,!0);z.ZE&&z.A||z.Qd(z.Oz(this.F),oI);break;default:z.B&&"+formatBlock"==a&&n&&(n="\x3c"+n+"\x3e");if("+foreColor"==a&&null===
n)break;switch(a){case "+indent":case "+outdent":z.ZE&&(z.A&&(g=!0),z.vg&&(g="+outdent"==a?!jI(this).queryCommandEnabled("outdent"):!0));case "+insertOrderedList":case "+insertUnorderedList":if(t=z.gF)t=jI(this),t=GI(this,!0,t,a,void 0);t?h="P"!=this.F.queryCommandValue("+defaultTag"):z.hF||kI(this);z.A&&z.fF&&!this.queryCommandValue(a)&&(t=this.F.queryCommandValue("+defaultTag"),"P"==t||"DIV"==t?t=!1:(t=this.ze(),t.isCollapsed()&&3!=t.tc().nodeType?(f=pH(this).createTextNode(" "),t.insertNode(f,
!1),z.tu(f).select(),t=!0):t=!1),k|=t);case "+formatBlock":f=!!this.F.Pb.Bidi;break;case "+subscript":case "+superscript":z.eF&&!this.queryCommandValue(a)&&(t="+subscript"==a?"+superscript":"+subscript",x=nI(t),this.queryCommandValue(t)||jI(this).execCommand(x,!1,null),jI(this).execCommand(x,!1,null));break;case "+underline":case "+bold":case "+italic":g=z.A&&z.ZE&&this.queryCommandValue(a);break;case "+foreColor":case "+fontName":g=z.ZE&&z.A}pI(this,a,n,f,!!g);k&&jI(this).execCommand("Delete",!1,
!0);h&&jI(this).execCommand("FormatBlock",!1,"\x3cdiv\x3e")}z.A&&!this.F.Sg&&pH(this).Ta().focus();return m};
z.e.queryCommandValue=function(a){var b;switch(a){case "+link":return a=(a=this.ze())&&a.Ob(),a=z.uf(a,"A"),!!a&&!!z.vf(a,BH);case "+justifyCenter":case "+justifyFull":case "+justifyRight":case "+justifyLeft":return DI(this,a);case "+formatBlock":return CI(z.Oz(this.F));case "+indent":case "+outdent":case "+insertHorizontalRule":return!1;case "+fontSize":case "+fontName":case "+foreColor":case "+backColor":return this.Mt(jI(this),a,z.ZE&&z.A);case "+underline":case "+bold":case "+italic":b=z.ZE&&
z.A;default:var c=jI(this);return GI(this,!0,c,a,b)}};z.e.kI=function(a){z.XE&&a.match(/^\s*<script/i)&&(a="\x26nbsp;"+a);z.YE&&(a=a.replace(/<(\/?)strong([^\w])/gi,"\x3c$1b$2"),a=a.replace(/<(\/?)em([^\w])/gi,"\x3c$1i$2"));return a};z.e.PM=function(a){a=a.getElementsByTagName("IMG");for(var b=0,c;c=a[b];b++)if(z.B){c.removeAttribute("tabIndex");c.removeAttribute("tabIndexSet");var d=c;null!==d&&"removeAttribute"in d&&d.removeAttribute(z.va);try{delete d[z.va]}catch(f){}c.FR&&(c.tabIndex=c.FR)}};
z.e.QM=function(a){if(z.C){for(var b=z.Me(this.F.eb.Ia,"HEAD",void 0,void 0),c=[],d=b.length,f=1;f<d;++f)for(var g=b[f].getElementsByTagName("STYLE"),h=g.length,k=0;k<h;++k)c.push(g[k].outerHTML);return c.join("")+a}return a};z.e.ds=function(a,b,c){if(!c)return!1;var d;switch(b){case "b":d="+bold";break;case "i":d="+italic";break;case "u":d="+underline";break;case "s":return!0}return d?(this.F.execCommand(d),!0):!1};
var lI=z.B?/<br([^\/>]*)\/?>/gi:/<br([^\/>]*)\/?>(?!<\/(div|p)>)/gi,rI={indent:1,outdent:1,insertOrderedList:1,insertUnorderedList:1,justifyCenter:1,justifyFull:1,justifyRight:1,justifyLeft:1,ltr:1,rtl:1},qI={insertOrderedList:1,insertUnorderedList:1},BI={1:1,a:1,A:1,i:1,I:1},AI={disc:1,circle:1,square:1},sI={justifyCenter:1,justifyFull:1,justifyRight:1,justifyLeft:1,formatBlock:1},tI={insertOrderedList:1,insertUnorderedList:1},FI={center:1,justify:1,right:1,left:1};
iI.prototype.Mt=function(a,b,c){return GI(this,!1,a,b,c)};z.v(HI,z.yc);HI.prototype.toString=function(){for(var a=[],b,c=0;b=this.mt[c];c++)a.push(this.rt[c]+","+b);return a.join("\n")};HI.prototype.D=function(){delete this.rt;delete this.mt};z.v(JI,z.nz);z.e=JI.prototype;z.e.tag="DIV";z.e.ld=function(){return"EnterHandler"};z.e.enable=function(a){JI.o.enable.call(this,a);!z.jF||"P"!=this.tag&&"DIV"!=this.tag||pH(this).ua().execCommand("opera-defaultBlock",!1,this.tag)};z.e.kI=function(a){return!a||z.mp(a)?z.XE?this.lO():"":a};z.e.lO=z.jb("\x3cbr\x3e");
z.e.gP=function(a){if(z.A&&this.F.Sg)return!1;if(8==a.keyCode){var b=z.Oz(this.F),c=this.F.m(),b=b&&b.Z();c.firstChild==b&&z.Bu(b)&&(a.preventDefault(),a.stopPropagation())}else if(13==a.keyCode)if(z.A){if(!a.shiftKey){var c=z.Oz(this.F),b=!c||c.isCollapsed(),d=MI(this),f=this.F.execCommand("+splitBlockquote",d);f&&(a.preventDefault(),a.stopPropagation());z.SE||d.removeNode(!0);f||this.UO(a,b,c)}}else{this.F.Uh();c=MI(this);if(b=!!this.F.execCommand("+splitBlockquote",c))a.preventDefault(),a.stopPropagation();
z.SE||c.removeNode(!0);z.C&&this.VO(a);if(z.B||z.vg)KI(this);else if(!b&&z.C){if(b=c=z.Oz(this.F))a:{for(b=c.Ob();b;b=b.parentNode)if(MH(b)){b="BLOCKQUOTE"==b.tagName;break a}b=!1}if(b){b=pH(this);d=b.createElement("BR");c.insertNode(d,!0);if(c=MH(d.parentNode)){for(c=d.nextSibling;c&&3==c.nodeType&&!c.nodeValue;)c=c.nextSibling;c=!c}c&&z.bf(b.createElement("BR"),d);z.Hu(d,!1);a.preventDefault()}}this.F.bf()}else z.A&&46==a.keyCode&&(b=z.Oz(this.F),b.isCollapsed()&&(c=b.la(),1==c.nodeType&&(b=c.childNodes[b.Ja()])&&
"BR"==b.tagName&&(d=z.zu(z.Wo(new z.wu(b,!1,!0),z.Au)),f=b.nextSibling,c.removeChild(b),a.preventDefault(),f&&MH(f)&&(d&&"BR"!=d.tagName&&!MH(d)?z.uu(d,z.Du(d)).select():(a=z.yu(f),z.uu(a,0).select())))));return!1};z.e.cs=function(a){if(z.A&&this.F.Sg)return!1;(z.B||z.vg)&&13==a.keyCode&&KI(this,!0);return!1};z.e.VO=z.p;z.e.UO=z.p;var LI={LI:!0,DIV:!0,H1:!0,H2:!0,H3:!0,H4:!0,H5:!0,H6:!0};var NK=new NI,OK=["click",z.A?"keypress":"keydown","keyup"];NI.prototype.g=function(a,b,c,d,f){function g(a){var c=z.dd(b),f=z.kf(a.target)?a.target.getAttribute("role")||null:null;"click"==a.type&&z.Uc(a)?c.call(d,a):13!=a.keyCode&&3!=a.keyCode||"keyup"==a.type?32!=a.keyCode||"keyup"!=a.type||"button"!=f&&"tab"!=f||(c.call(d,a),a.preventDefault()):(a.type="keypress",c.call(d,a))}g.Sj=b;g.du=d;f?f.g(a,OK,g,c):z.E(a,OK,g,c)};
NI.prototype.qa=function(a,b,c,d,f){for(var g,h=0;g=OK[h];h++){var k;var m=a;k=g;var n=!!c;k=z.Wc(m)?m.wl(k,n):m?(m=z.fd(m))?m.wl(k,n):[]:[];for(m=0;n=k[m];m++)if(n.listener.Sj==b&&n.listener.du==d){f?f.qa(a,g,n.listener,c,d):z.nd(a,g,n.listener,c,d);break}}};z.v(OI,z.F);OI.prototype.Ng=function(){return this.vc?this.vc.clone():null};OI.prototype.D=function(){OI.o.D.call(this);this.dz&&(z.od(this.dz),this.dz=null);this.vc=this.Qu=null};OI.prototype.$x=function(){var a=z.Pe(this.Qu);z.Po(a,this.vc)||(this.vc=a,this.dispatchEvent("resize"))};z.v(PI,z.F);var QI="tr_bubble";z.e=PI.prototype;z.e.D=function(){PI.o.D.call(this);z.O(this.Dd);this.Dd=null;this.T.H();this.T=null;this.LB.H();this.LB=null};z.e.R=function(){return this.bn};z.e.Ob=function(){return this.Dd};z.e.OP=function(){this.V()&&this.ha()};z.e.mm=function(a){this.jg.mm(a)};z.e.rD=function(){this.jg.G(!1)};z.e.wP=function(){for(var a in this.sd)z.O(this.sd[a].element);this.sd={};z.ij(this.Dd,"tr_multi_bubble");this.T.removeAll();this.dispatchEvent("hide")};z.e.V=function(){return this.jg.V()};
var PK=z.B?4:2,TI=new z.qg(PK,0,PK,0);PI.prototype.ha=function(){var a=null,b=!0,c;for(c in this.sd)var d=this.sd[c],a=d.gB,b=b&&d.BT;c=496;a=z.Ng(this.Dd)!=z.Ng(a);b&&(c=SI(this,a?7:5,4,9));c&496&&(c=SI(this,a?6:4,5,9));c&496&&SI(this,a?7:5,4,5)};PI.prototype.oO=z.Hl;UI.prototype.R=function(){return this.element.lastChild};z.v(VI,z.nz);var YI={};z.e=VI.prototype;z.e.mi=null;z.e.Uy=!1;z.e.ld=z.jb("AbstractBubblePlugin");z.e.cs=function(){this.V()&&this.Bj();return!1};
z.e.Bj=function(a,b){var c;if(a)c=a.target;else if(b)c=b;else{var d=z.Oz(this.F);if(d){var f=d.Z(),g=d.la(),h=d.va(),k=d.Ja();z.B&&d.isCollapsed()&&f!=g&&(d=z.uu(f,h));1==f.nodeType&&f==g&&h==k-1&&(f=f.childNodes[h],1==f.nodeType&&(c=f))}c=c||d&&d.Ob()}var m;a:{if(c){if(d=c)d="IMG"==c.nodeName&&(!!c.getAttribute("eeimg")||z.fj(c,"ee_img"));if(h=d?c:null){if(h!=this.xu||!this.mi)if(this.mi&&ZI(this),c=XI(this),!RI(c,this.zx())){this.xu=h;var f=this.zx(),k=this.XE(),g=(0,z.q)(this.gN,this),n=this.UU(),
d=z.hp(),h=new UI(c.da,d,f,k,h,!n);c.sd[d]=h;k=0;for(n=c.bn.childNodes.length-1;k<n;k++){var t=c.bn.childNodes[k];if(c.sd[t.id].type>f){m=t;break}}z.bf(h.element,m||c.bn.lastChild);g(h.R());JH(h.element,c.T);m=z.Xn(c.sd);1==m?(c.T.g(c.qD,"click",c.rD).g(c.LB,"resize",c.OP).g(c.jg,"hide",c.wP),c.jg.G(!0),c.ha()):2==m&&z.gj(c.Dd,"tr_multi_bubble");c.ha();this.mi=d;this.ec.g(c,"hide",this.yF);this.fg();this.Uy&&this.ec.g(c.R(),"keydown",this.SR)}m=!1;break a}}this.mi&&ZI(this);m=!1}return m};
z.e.disable=function(a){if(a.Sl==z.zz){var b=YI[a.id];b&&(a==this.F&&ZI(this),b.H(),delete YI[a.id])}};z.e.zx=function(){return""};z.e.XE=function(){return""};z.e.UU=z.Fl;z.e.fg=z.p;z.e.RM=z.p;z.e.yF=function(){this.mi=this.xu=null;this.ec.removeAll();this.RM()};z.e.Xx=function(a){if(this.Uy&&this.V()&&9==a.keyCode&&!a.shiftKey){var b=XI(this).R();if(b=z.L("tr_bubble_tabbable",b))return b.focus(),a.preventDefault(),!0}return!1};
z.e.SR=function(a){if(this.V()&&9==a.keyCode){var b=XI(this).R(),b=z.Oo("tr_bubble_tabbable",b);(a.shiftKey?b[0]:z.lb(b))==a.target&&(this.F.focus(),a.preventDefault())}};z.e.V=function(){return!!this.mi};z.e.ha=function(){var a=XI(this);a&&a.ha()};
z.e.lr=function(a,b,c,d){b=this.da.B("SPAN",{className:"tr_bubble_link"},b);this.Uy&&(b.hasAttribute("tabindex")||b.setAttribute("tabindex",0),z.gj(b,"tr_bubble_tabbable"));b.setAttribute("role","link");d?d.appendChild(b):(d=this.da.m(a))&&z.No(b,d);b.id=a;JH(b,this.ec);c&&(a=this.ec,NK.g(b,c,void 0,a.ga||a,a));return b};z.v(aJ,VI);var QK=z.u("Equation:"),RK=z.u("Edit"),SK=z.u("Remove");z.e=aJ.prototype;z.e.ld=function(){return"EquationBubble"};z.e.gN=function(a){a.appendChild(a.ownerDocument.createTextNode(QK+" "));this.lr("ee_bubble_edit",RK,this.FN,a);a.appendChild(a.ownerDocument.createTextNode(QK+" - "));this.lr("ee_remove_remove",SK,this.WT,a)};z.e.zx=function(){return"IMG"};z.e.XE=function(){return z.u("Equation")};z.e.WT=function(){this.F.Uh();z.O(this.xu);ZI(this);this.F.bf()};
z.e.FN=function(){var a=this.xu;ZI(this);this.F.execCommand("+equation",a)};z.v(bJ,z.Mc);bJ.prototype.type="ok";z.v(cJ,z.Mc);z.v(dJ,z.Q);dJ.prototype.Cj="";dJ.prototype.G=function(a){z.P(this.m(),a)};z.v(eJ,z.uD);z.e=eJ.prototype;z.e.ci=function(){return this.Vb};z.e.ql=function(a){return 0<=a&&a<this.Om.length?this.Om[a]:null};z.e.mf=function(a){eJ.o.mf.call(this,a);this.hg.dispatchEvent(new gJ(TK,this))};z.e.Cl=function(a){eJ.o.Cl.call(this,a);a.relatedTarget&&!z.mf(this.m(),a.relatedTarget)&&this.hg.pr()};z.e.md=function(a){eJ.o.md.call(this,a);a.relatedTarget&&!z.mf(this.m(),a.relatedTarget)&&this.hg.Gw.stop()};var TK="a";gJ.prototype.Hx=function(){return this.nT};z.v(fJ,z.mD);z.la(fJ);
fJ.prototype.U=function(){return"ee-palette"};z.v(hJ,dJ);z.e=hJ.prototype;z.e.HG="";z.e.jw=0;
z.e.B=function(){var a=z.u("TeX 公式"),b=z.u("预览"),c=z.u("了解更多"),d=this.da,c=d.B("DIV",{style:"display: none;"},d.B("SPAN",{"class":"ee-section-title ee-section-title-floating"},a),this.Cj?d.B("A",{id:"ee-section-learn-more",target:"_blank",href:this.Cj},c):null,d.B("DIV",{style:"clear: both;"}),a=this.pQ=d.B("DIV",{style:"position: relative"}));this.hg.setActive("mn").render(a);a.appendChild(d.B("DIV",{style:"clear:both"}));var f=this.uh=d.B("textarea",{"class":"ee-tex",dir:"ltr"});a.appendChild(f);
a.appendChild(d.B("DIV",{"class":"ee-section-title"},b));b=this.GT=d.B("DIV",{"class":"ee-preview-container"});a.appendChild(b);this.h=c};z.e.C=function(){this.CJ=new z.VC(this.uh);z.E(this.CJ,"input",this.AF,!1,this);this.v().g(this.uh,"keydown",this.AF);this.v().g(this.hg,TK,this.vP)};z.e.G=function(a){hJ.o.G.call(this,a);a&&z.wd(this.aO,0,this)};z.e.aO=function(){this.uh.focus();z.ts(this.uh,this.uh.value.length)};z.e.AF=function(){this.jw++;z.wd((0,z.q)(this.DP,this,this.jw),500)};
z.e.DP=function(a){a==this.jw&&iJ(this)};z.e.vP=function(a){var b=a.Hx(),c=this.hg,d=c.Pm;a=this.uh;if("mn"==b.ci()){var f=b.Ra,f=-1!=f?b.ql(f):null;if(d!=b&&d.ci()==f){c.nF();return}f&&(b=this.hg.setActive(f),b.m()||b.render(this.pQ),b=b.m(),z.Ag(b,0,-b.clientHeight))}else{d=this.hg.Pm;f=d.ql(d.Ra);if(!f)return;z.wd((0,z.q)(this.yQ,this,f+" "),0)}a.focus()};z.e.yQ=function(a){var b=this.uh,c=z.qs(b)[0],d=b.value,d=d.substring(0,c)+a+d.substring(c);b.value=d;z.ts(b,c+a.length);iJ(this)};z.e.ul=function(){return this.uh.value};
z.e.EA=function(a){this.uh.value=a;iJ(this)};z.e.D=function(){this.CJ.H();this.hg=null;hJ.o.D.call(this)};z.v(jJ,z.Q);z.e=jJ.prototype;z.e.vh=null;z.e.B=function(){jJ.o.B.call(this);this.jr()};z.e.jr=function(){var a=this.m();this.vh=new hJ(this.ED,this.Cj,this.da);this.L(this.vh);this.vh.render(a);this.vh.G(!0)};z.e.X=function(a){this.h=a;this.jr()};z.e.ul=function(){return this.vh.ul()};z.e.EA=function(a){this.vh.EA(a)};z.e.Gx=function(){var a=this.ul(),b=$I(a);return b?'\x3cimg src\x3d"'+b+'" alt\x3d"'+z.Oa(a)+'" class\x3d"ee_img tr_noresize" eeimg\x3d"1" style\x3d"vertical-align: middle"\x3e':""};
z.e.isValid=function(){return 1024<this.ul().length};z.e.G=function(a){this.vh.G(a)};z.e.D=function(){this.vh&&this.vh.H();this.ED=null;jJ.o.D.call(this)};z.v(kJ,UH);kJ.prototype.vw=function(){var a=new VH(this),b=z.u("公式编辑器"),c=z.u("插入公式"),d=z.u("保存修改"),f=z.u("取消"),c=this.lj.ul()?d:c;WH(XH(a.La(b).ia(this.lj.m()),f),c);return YH(a)};kJ.prototype.sn=function(){if(this.lj.isValid())return null;var a=this.lj.Gx();return new bJ(a)};kJ.prototype.Dz=function(a){this.uH||(this.uH=this.Ax("ok"));this.uH.disabled=!a.isValid};z.v(lJ,eJ);z.v(mJ,eJ);z.v(nJ,eJ);z.v(oJ,eJ);z.v(pJ,eJ);pJ.prototype.G=function(a,b){return pJ.o.G.call(this,!0,b)};z.v(qJ,fJ);z.la(qJ);qJ.prototype.U=function(){return"ee-menu-palette"};z.v(rJ,eJ);z.v(sJ,z.F);z.e=sJ.prototype;z.e.Hx=function(a){var b=this.dI,c=b[a];if(!c){switch(a){case "mn":c=new pJ(this);break;case "g":c=new nJ(this);break;case "s":c=new rJ(this);break;case "c":c=new mJ(this);break;case "m":c=new oJ(this);break;case "a":c=new lJ(this);break;default:throw Error("Invalid palette type!");}b[a]=c}return c};z.e.setActive=function(a){var b=this.Pm;b&&b.G(!1);this.Pm=b=this.Hx(a);b.G(!0);return b};z.e.pr=function(){this.Gw.start()};z.e.nF=function(){this.setActive("mn")};
z.e.K=function(){return this.DN};z.e.D=function(){sJ.o.D.call(this);this.dI=this.Pm=null};z.v(tJ,$H);z.e=tJ.prototype;z.e.ld=z.jb("EquationEditorPlugin");z.e.uw=function(a,b){var c=b||null,d;c?(d=c.getAttribute("alt"),d||(d=(d=c.getAttribute("src"))?z.ce(d,"tex")||"":"")):d="";this.bI=c;c={};c.mT=new sJ(a);c=new kJ(c,a,d,this.Cj);c.addEventListener("ok",this.Xn,!1,this);return c};z.e.enable=function(a){tJ.o.enable.call(this,a);this.isEnabled(a)&&(this.pN=z.E(a.m(),"dblclick",(0,z.q)(this.JO,this),!1,this))};z.e.disable=function(a){tJ.o.disable.call(this,a);this.isEnabled(a)||z.od(this.pN)};
z.e.JO=function(a){(a=a.target)&&"IMG"===a.nodeName&&a.getAttribute("eeimg")&&this.execCommand("+equation",a)};z.e.Xn=function(a){aI(this);this.F.Uh();a=z.Ye(pH(this).Ia,a.RN);if(this.bI)z.No(a,this.bI);else{var b=z.Oz(this.F);b.isCollapsed()||b.Zc();a=b.insertNode(a,!1)}z.Hu(a,!1);this.F.bf()};z.v(uJ,z.nz);uJ.prototype.ds=function(a){return z.A&&this.F.Sg?!1:9!=a.keyCode||a.metaKey||a.ctrlKey?!1:wJ(this,a)};z.v(vJ,uJ);vJ.prototype.ld=function(){return"ListTabHandler"};z.v(xJ,z.nz);z.e=xJ.prototype;z.e.ld=z.jb("LoremIpsum");z.e.xq=z.Gl;z.e.fq=!1;z.e.queryCommandValue=function(a){return"usinglorem"==a&&this.fq};
z.e.execCommand=function(a,b){if("clearlorem"==a){var c=!!b,d=this.F;if(this.fq&&!d.Sg){var f=d.m();f||(f=d.Hc);this.fq=!1;f.style.fontStyle=this.ER;d.Pd(!0,null,!0);c&&d.uc()&&(z.C?(z.Ke(d.m()).body.focus(),d.Tf()):z.vg&&z.Uz(d))}}else"updatelorem"==a&&(c=this.F,this.fq||c.Sg||z.yF==c.id||((d=c.m())||(d=c.Hc),z.Bu(d)&&(this.fq=!0,this.ER=d.style.fontStyle,d.style.fontStyle="italic",c.Pd(!0,this.sR,!0))))};z.e.Ge=function(a){return"clearlorem"==a||"updatelorem"==a||"usinglorem"==a};z.v(yJ,z.F);z.v(zJ,z.F);z.e=zJ.prototype;z.e.ts=null;z.e.xB=function(){AJ(this,this.Sd,this.lk)};z.e.kA=function(){AJ(this,this.lk,this.Sd)};z.e.Fg=function(){if(!this.ts&&0!=this.Dt.length){var a=this.Dt.shift();this.dispatchEvent({type:a.type,state:a.state})&&(a.state.lM?(this.ts=z.E(a.state,"action_completed",this.WN,!1,this),a.UE.call(a.state)):(a.UE.call(a.state),this.Fg()))}};z.e.WN=function(){z.od(this.ts);this.ts=null;this.Fg()};z.v(BJ,z.nz);BJ.prototype.eo=null;var UK=z.Yo({mX:"+undo",aX:"+redo"});z.e=BJ.prototype;z.e.Ge=function(a){return a in UK};z.e.WJ=function(a){this.disable(a);this.F=null};z.e.enable=function(a){if(!this.isEnabled(a)){z.Rz(a);var b=new z.yd(this);z.A||b.g(a,"beforechange",this.xO);b.g(a,z.vz,this.EO);b.g(a,"blur",this.Nx);this.mj[a.Qg]=b;CJ(this,a)}};z.e.disable=function(a){z.Rz(a);var b=this.mj[a.Qg];b&&(b.H(),delete this.mj[a.Qg]);this.xn[a.Qg]&&delete this.xn[a.Qg]};z.e.isEnabled=function(a){return!!this.mj[a.Qg]};
z.e.D=function(){BJ.o.D.call(this);for(var a in this.mj)this.mj[a].H(),delete this.mj[a];this.F=null;this.Ef&&(this.Ef.H(),delete this.Ef)};z.e.ld=function(){return"UndoRedo"};z.e.execCommand=function(a){"+undo"==a?this.Ef.xB():"+redo"==a&&this.Ef.kA()};z.e.queryCommandValue=function(a){var b=null;"+undo"==a?b=0<this.Ef.Sd.length:"+redo"==a&&(b=0<this.Ef.lk.length);return b};z.e.zN=function(){this.F.dispatchEvent({type:"cvc",ZM:["+redo","+undo"]})};
z.e.jU=function(a,b,c){var d=this.F;if(d){z.Qz(d,!0,!0);try{d.Uh();d.execCommand("clearlorem",!0);z.Eu(d.m(),b);c&&c.select();var f=this.F;d.focus();f&&f.Qg!=a.Fn&&f.execCommand("updatelorem");var g=this.xn[a.Fn];g.Ei=b;g.TJ=c}catch(h){}finally{this.eo=a,d.bf(),z.Pz(d)}}};
z.e.ds=function(a,b,c){if(c){var d;"z"==b?d=a.shiftKey?"+redo":"+undo":"y"==b&&(d="+redo");if(d)return"+undo"==d?(a=this.Ef,a=a.Sd[a.Sd.length-1]):(a=this.Ef,a=a.lk[a.lk.length-1]),a&&a.Fn?this.F.execCommand(d):this.execCommand(d),!0}return!1};z.e.xO=function(a){if(!this.eo){a=a.target;var b=a.Qg;this.cG!=b&&(this.cG=b,CJ(this,a))}};z.e.EO=function(a){this.eo?(a=this.eo,this.eo=null,a.dispatchEvent("action_completed")):CJ(this,a.target)};z.e.Nx=function(a){(a=a.target)&&z.Rz(a)};z.v(EJ,yJ);
EJ.prototype.xB=function(){this.MI(this,this.Ei,this.TJ)};EJ.prototype.kA=function(){this.MI(this,this.lA,this.QT)};EJ.prototype.equals=function(a){return this.Fn==a.Fn&&this.Ei==a.Ei&&this.lA==a.lA};DJ.prototype.isValid=function(){return this.Is};DJ.prototype.toString=function(){return z.SE?"W3C:"+this.Ca.toString()+"\n"+this.WA+":"+this.Ba.toString()+"\n"+this.Yw:"IE:"+this.Ca+","+this.Ba};DJ.prototype.select=function(){var a=this.ze(this.$d.m());a&&(z.RE&&this.$d.m().focus(),z.su(a).select())};
DJ.prototype.ze=function(a){if(z.SE){var b=II(this.Ca,a);a=II(this.Ba,a);return b&&a?z.bu(b,this.WA,a,this.Yw).ce():null}b=a.ownerDocument.body.createTextRange();b.moveToElementText(a);b.collapse(!0);b.moveEnd("character",this.Ba);b.moveStart("character",this.Ca);return b};z.v(GJ,z.F);z.e=GJ.prototype;z.e.v=function(){return this.ga};z.e.Cx=function(){return this.$d};z.e.V=function(){return this.Eb.V()};z.e.G=function(a){this.Eb.G(a)};z.e.isEnabled=function(){return this.Eb.isEnabled()};z.e.Ua=function(a){this.Eb.Ua(a)};z.e.blur=function(){this.Eb.Xc(null)};z.e.D=function(){GJ.o.D.call(this);this.ga&&(this.ga.H(),delete this.ga);this.Eb&&(this.Eb.H(),delete this.Eb);delete this.$d;delete this.gA};
z.e.XV=function(a){if(this.Eb.isEnabled()&&this.dispatchEvent("change")){var b;try{b=this.$d.queryCommandValue(a.ZM||this.gA)}catch(f){b={}}a=b;for(var c in a)if(b=z.$g(this.Eb,c)){var d=a[c];b.Gi?b.Gi(d):b.Jc(!!d)}}};z.e.sO=function(a){var b=a.target.de();this.$d.execCommand(b,a.target.Y())};z.v(IJ,z.hy);z.Rp("goog-toolbar-separator",function(){return new IJ});z.v(JJ,z.nz);z.e=JJ.prototype;z.e.defaults={SX:z.p};z.e.ld=z.jb("FastUpload");
z.e.enable=function(a){if(!this.isEnabled(a)&&(window.URL||window.webkitURL)&&window.FileReader&&window.FormData&&window.document.addEventListener){window.$.fn.draghover=function(){return this.each(function(){var a=(0,window.$)(),b=(0,window.$)(this),f=!0;b.on("dragenter",function(g){g=g.originalEvent;0===a.size()&&f&&z.y(g.dataTransfer.types,"Files")&&b.trigger("draghoverstart",g);a=a.add(g.target)});b.on("dragleave",function(g){(0,window.setTimeout)(function(){a=a.not(g.target);0===a.size()&&f&&
b.trigger("draghoverend",g)},1)});b.on("dragstart",function(){f=!1});b.on("drop dragend",function(){a=(0,window.$)();b.trigger("draghoverend");f=!0})})};this.VB=(0,window.$)(this.F.m());var b=this.GK=KJ(this);new z.yd(this);a.m().addEventListener("paste",(0,z.q)(this.Zx,this));window.document.addEventListener("dragover",(0,z.q)(this.SO,this),!1);b.on("dragover",(0,z.q)(this.RO,this));b.get(0).addEventListener("drop",(0,z.q)(this.as,this),!1);(0,window.$)(window).draghover().on({draghoverstart:(0,z.q)(this.pF,
this),draghoverend:(0,z.q)(this.TO,this)});b.draghover().on({draghoverstart:(0,z.q)(this.LO,this),draghoverend:(0,z.q)(this.pF,this)})}};z.e.SO=function(a){z.y(a.dataTransfer.types,"Files")&&(a.dataTransfer.dropEffect="none",a.preventDefault())};z.e.RO=function(a){a=a.originalEvent;a.dataTransfer.dropEffect="copy";a.preventDefault();a.stopPropagation()};z.e.pF=function(a){a.preventDefault();a.stopPropagation();MJ(this,1)};z.e.LO=function(a){MJ(this,2);a.stopPropagation()};
z.e.TO=function(a){a.preventDefault();MJ(this,0)};z.e.Zx=function(a){var b=this;a.clipboardData&&z.y(a.clipboardData.types,"Files")&&1===a.clipboardData.items.length&&z.w(a.clipboardData.items,function(c){-1<c.type.indexOf("image")&&(NJ(b,c.getAsFile()),a.preventDefault())})};
z.e.as=function(a){var b=this;b.F.execCommand("clearlorem");var c=a.dataTransfer.files;a.preventDefault();var d=[];z.w(c,function(a){-1<a.type.indexOf("image")?(NJ(b,a),d.push(!0)):d.push(!1)});z.Yn(d,function(a){return!a})&&z.W.message("文件类型不支持！");MJ(b,0)};var VK={};
(function(){function a(a,c,d){function t(a){z.ef(a)}function ca(b,c){for(;b!==a;){if(c(b))return b;b=b.parentNode}return null}function Wa(a){return a.tagName&&a.tagName===c}if(!a)throw"Missing Editable Container";c||(c="blockquote");c=c.toUpperCase();var bb=z.qu();if(function(b){return b&&g(a,z.zt(b))&&g(a,z.Bt(b))}(bb)){var Ha=h(bb),ya=k(bb),zd=bb.Ob(),bi=ca(zd,Wa),je=z.pb(ya,function(a,b){1===b.nodeType&&(Wa(b)?a.push(b):a.push.apply(a,z.wb(b.getElementsByTagName(c))));return a},[]),Hd;if(bi){if(d)return n.qv;
z.ef(bi)}else if(je.length){if(d)return n.qv;z.w(je,t)}else{if(d)return n.mC;if(d=ca(zd,function(a){return z.y(m,a.tagName.toLowerCase())}))Hd=window.document.createElement(c),d.parentNode.insertBefore(Hd,d),Hd.appendChild(d);else if(bb.Z()!==bb.la())Hd=window.document.createElement(c),ya[0].parentNode.insertBefore(Hd,ya[0]),z.w(ya,function(a){Hd.appendChild(a)});else return f(a,c)}b(a,Ha)}else if(d)return n.mC}function b(a,b){if(b){var c=function(b,c){return b&&g(a,b)&&z.Du(b)>=c};c(b.Z(),b.va())&&
c(b.la(),b.Ja())&&b.select()}}function c(a){return a&&"BR"===a.tagName||MH(a)||wH(a)}function d(a){a=z.vf(a,function(a){a=a.parentNode;return MH(a)||wH(a)},!0);var b=QH(new z.wu(a,!0,!0),z.cp(c));a=QH(new z.wu(a,!1,!1),z.cp(c));return z.Rd(b).reverse().concat(z.Rd(a))}function f(a,b){if(t.uL)window.document.execCommand("formatBlock",!1,b);else{var c=z.qu(),f=c.tc();if(z.kf(f)&&z.Bu(f))c=window.document.createElement(b),f===a?f.appendChild(c):z.No(c,f),(z.C||z.A)&&c.appendChild(window.document.createElement("br")),
z.Gu(c);else if(f=c.la(),f=d(f),f.length){var c=window.document.createElement(b),g=z.lb(f),h=g.nextSibling;h&&h&&"BR"===h.tagName&&z.O(h);z.cf(c,g);z.$e(c,f);(z.C||z.A)&&c.appendChild(window.document.createElement("br"));z.Hu(c.lastChild)}}}function g(a,b){return 3===a.nodeType?a===b:a.contains(3===b.nodeType?b.parentNode:b)}function h(a){return rH(a.Z(),a.va(),a.la(),a.Ja())}function k(a){function b(a){return!(a.previousSibling&&g(a.previousSibling,h))}function c(a){return f!==d&&!g(a,f)}if(a.isCollapsed())return[];
var d=a.tc(),f=a.Z(),h=a.la();a=d.childNodes;return z.Rd(1===a.length?a:QH(RH(a,c),b))}var m=["ul","ol","dl","table"],n={qv:1,mC:0},t=VK;t.uL=!z.B;t.toggle=a;t.getState=function(b,c){return a(b,c,!0)};t.pL=n})();z.v(OJ,z.nz);z.e=OJ.prototype;z.e.ld=z.jb("Blockquote");z.e.Ge=function(a){return"+blockquote"===a};z.e.ef=function(a){this.Ge(a)&&VK.toggle(this.F.m())};z.e.queryCommandValue=function(){return VK.pL.qv===VK.getState(this.F.m())};z.e.Xx=function(a){if(13===a.keyCode)return this.Tx(a)};z.e.KA=function(a,b){return QJ(a,b).KA};
z.e.Tx=function(a){var b=z.Oz(this.F);if(b.isCollapsed()){var c;a:{c=b.la();for(var d=this.F.Ea;c!==d;){if("BLOCKQUOTE"===c.tagName)break a;c=c.parentNode}c=void 0}if(c&&(b=QJ(c,b),b.KA)){a.preventDefault();a=window.document.createElement("div");z.cf(a,c);if(z.C||z.A)c=c.nextSibling,(c=PJ(c)&&c)||(c=window.document.createElement("br")),a.appendChild(c);z.uu(a,0).select();b.qH&&z.O(b.qH)}}};z.tG["+blockquote"]={hb:!0,S:"引用内容",Aa:"+blockquote",Na:"tr-icon tr-blockquote",factory:z.iE};z.v(SJ,z.Q);
var VJ=[["ABAP","abap"],["ABNF","abnf"],["ActionScript 3","as3"],["ActionScript","as"],["Ada","ada"],["ADL","adl"],["Agda","agda"],["Alloy","alloy"],["AmbientTalk","at"],["ANTLR","antlr"],["ApacheConf","apacheconf"],["APL","apl"],["AppleScript","applescript"],["Arduino","arduino"],["AspectJ","aspectj"],["aspx-cs","aspx-cs"],["aspx-vb","aspx-vb"],["Asymptote","asy"],["autohotkey","ahk"],["AutoIt","autoit"],["Awk","awk"],["Base Makefile","basemake"],["Bash Session","console"],["Bash","bash"],["Batchfile",
"bat"],["BBCode","bbcode"],["BC","bc"],["Befunge","befunge"],["BlitzBasic","blitzbasic"],["BlitzMax","blitzmax"],["BNF","bnf"],["Boo","boo"],["Boogie","boogie"],["Brainfuck","brainfuck"],["Bro","bro"],["BUGS","bugs"],["C","c"],["C#","csharp"],["C++","cpp"],["c-objdump","c-objdump"],["ca65 assembler","ca65"],["cADL","cadl"],["CAmkES","camkes"],["CBM BASIC V2","cbmbas"],["Ceylon","ceylon"],["CFEngine3","cfengine3"],["cfstatement","cfs"],["ChaiScript","chai"],["Chapel","chapel"],["Cheetah","cheetah"],
["Cirru","cirru"],["Clay","clay"],["Clojure","clojure"],["ClojureScript","clojurescript"],["CMake","cmake"],["COBOL","cobol"],["COBOLFree","cobolfree"],["CoffeeScript","coffee-script"],["Coldfusion CFC","cfc"],["Coldfusion HTML","cfm"],["Common Lisp","common-lisp"],["Component Pascal","componentpascal"],["Coq","coq"],["cpp-objdump","cpp-objdump"],["CPSA","cpsa"],["Crmsh","crmsh"],["Croc","croc"],["Cryptol","cryptol"],["Csound Document","csound-document"],["Csound Orchestra","csound"],["Csound Score",
"csound-score"],["CSS","css"],["CUDA","cuda"],["Cypher","cypher"],["Cython","cython"],["D","d"],["d-objdump","d-objdump"],["Darcs Patch","dpatch"],["Dart","dart"],["Debian Control file","control"],["Debian Sourcelist","sourceslist"],["Delphi","delphi"],["dg","dg"],["Diff","diff"],["Django/Jinja","django"],["Docker","docker"],["DTD","dtd"],["Duel","duel"],["Dylan session","dylan-console"],["Dylan","dylan"],["DylanLID","dylan-lid"],["Earl Grey","earl-grey"],["Easytrieve","easytrieve"],["EBNF","ebnf"],
["eC","ec"],["ECL","ecl"],["Eiffel","eiffel"],["Elixir iex session","iex"],["Elixir","elixir"],["Elm","elm"],["EmacsLisp","emacs"],["Embedded Ragel","ragel-em"],["ERB","erb"],["Erlang erl session","erl"],["Erlang","erlang"],["Evoque","evoque"],["Ezhil","ezhil"],["Factor","factor"],["Fancy","fancy"],["Fantom","fan"],["Felix","felix"],["Fish","fish"],["Fortran","fortran"],["FortranFixed","fortranfixed"],["FoxPro","foxpro"],["FSharp","fsharp"],["GAP","gap"],["GAS","gas"],["Genshi Text","genshitext"],
["Genshi","genshi"],["Gettext Catalog","pot"],["Gherkin","cucumber"],["GLSL","glsl"],["Gnuplot","gnuplot"],["Go","go"],["Golo","golo"],["GoodData-CL","gooddata-cl"],["Gosu Template","gst"],["Gosu","gosu"],["Groff","groff"],["Groovy","groovy"],["Haml","haml"],["Handlebars","handlebars"],["Haskell","haskell"],["Haxe","hx"],["Hexdump","hexdump"],["HTML","html"],["HTML+Django/Jinja","html+django"],["HTML+Handlebars","html+handlebars"],["HTTP","http"],["Hxml","haxeml"],["Hy","hylang"],["Hybris","hybris"],
["IDL","idl"],["Idris","idris"],["Igor","igor"],["Inform 6 template","i6t"],["Inform 6","inform6"],["Inform 7","inform7"],["INI","ini"],["Io","io"],["Ioke","ioke"],["IRC logs","irc"],["Isabelle","isabelle"],["J","j"],["Jade","jade"],["JAGS","jags"],["Jasmin","jasmin"],["Java Server Page","jsp"],["Java","java"],["JavaScript","js"],["JCL","jcl"],["JSON","json"],["JSON-LD","jsonld"],["Julia console","jlcon"],["Julia","julia"],["Kal","kal"],["Kconfig","kconfig"],["Koka","koka"],["Kotlin","kotlin"],["Lasso",
"lasso"],["Lean","lean"],["LessCss","less"],["Lighttpd configuration file","lighty"],["Limbo","limbo"],["liquid","liquid"],["Literate Agda","lagda"],["Literate Cryptol","lcry"],["Literate Haskell","lhs"],["Literate Idris","lidr"],["LiveScript","live-script"],["LLVM","llvm"],["Logos","logos"],["Logtalk","logtalk"],["LSL","lsl"],["Lua","lua"],["Makefile","make"],["Mako","mako"],["MAQL","maql"],["Mask","mask"],["Mason","mason"],["Mathematica","mathematica"],["Matlab session","matlabsession"],["Matlab",
"matlab"],["MiniD","minid"],["Modelica","modelica"],["Modula-2","modula2"],["MoinMoin/Trac Wiki markup","trac-wiki"],["Monkey","monkey"],["MOOCode","moocode"],["MoonScript","moon"],["mozhashpreproc","mozhashpreproc"],["mozpercentpreproc","mozpercentpreproc"],["MQL","mql"],["Mscgen","mscgen"],["MSDOS Session","doscon"],["MuPAD","mupad"],["MXML","mxml"],["Myghty","myghty"],["MySQL","mysql"],["NASM","nasm"],["Nemerle","nemerle"],["nesC","nesc"],["NewLisp","newlisp"],["Newspeak","newspeak"],["Nginx configuration file",
"nginx"],["Nimrod","nimrod"],["Nit","nit"],["Nix","nixos"],["NSIS","nsis"],["NumPy","numpy"],["objdump","objdump"],["objdump-nasm","objdump-nasm"],["Objective-C","objective-c"],["Objective-C++","objective-c++"],["Objective-J","objective-j"],["OCaml","ocaml"],["Octave","octave"],["ODIN","odin"],["Ooc","ooc"],["Opa","opa"],["OpenEdge ABL","openedge"],["PacmanConf","pacmanconf"],["Pan","pan"],["ParaSail","parasail"],["Pawn","pawn"],["Perl","perl"],["Perl6","perl6"],["PHP","php"],["Pig","pig"],["Pike",
"pike"],["PkgConfig","pkgconfig"],["PL/pgSQL","plpgsql"],["PostgreSQL console (psql)","psql"],["PostgreSQL SQL dialect","postgresql"],["PostScript","postscript"],["POVRay","pov"],["PowerShell Session","ps1con"],["PowerShell","powershell"],["Praat","praat"],["Prolog","prolog"],["Properties","properties"],["Protocol Buffer","protobuf"],["Puppet","puppet"],["PyPy Log","pypylog"],["Python 3","python3"],["Python 3.0 Traceback","py3tb"],["Python console session","pycon"],["Python Traceback","pytb"],["Python",
"python"],["QBasic","qbasic"],["QML","qml"],["QVTO","qvto"],["Racket","racket"],["Ragel","ragel"],["RConsole","rconsole"],["Rd","rd"],["REBOL","rebol"],["Red","red"],["Redcode","redcode"],["reg","registry"],["ResourceBundle","resource"],["reStructuredText","rst"],["Rexx","rexx"],["RHTML","rhtml"],["Roboconf Graph","roboconf-graph"],["Roboconf Instances","roboconf-instances"],["RobotFramework","robotframework"],["RPMSpec","spec"],["RQL","rql"],["RSL","rsl"],["Ruby irb session","rbcon"],["Ruby","rb"],
["Rust","rust"],["S","splus"],["Sass","sass"],["Scala","scala"],["Scalate Server Page","ssp"],["Scaml","scaml"],["Scheme","scheme"],["Scilab","scilab"],["SCSS","scss"],["Shen","shen"],["Slim","slim"],["Smali","smali"],["Smalltalk","smalltalk"],["Smarty","smarty"],["Snobol","snobol"],["SourcePawn","sp"],["SPARQL","sparql"],["SQL","sql"],["sqlite3con","sqlite3"],["SquidConf","squidconf"],["Stan","stan"],["Standard ML","sml"],["SuperCollider","sc"],["Swift","swift"],["SWIG","swig"],["systemverilog",
"systemverilog"],["TADS 3","tads3"],["TAP","tap"],["Tcl","tcl"],["Tcsh Session","tcshcon"],["Tcsh","tcsh"],["Tea","tea"],["Termcap","termcap"],["Terminfo","terminfo"],["Terraform","terraform"],["TeX","tex"],["Text only","text"],["Thrift","thrift"],["Todotxt","todotxt"],["TrafficScript","rts"],["Treetop","treetop"],["Turtle","turtle"],["Twig","twig"],["TypeScript","ts"],["UrbiScript","urbiscript"],["Vala","vala"],["VB.net","vb.net"],["VCTreeStatus","vctreestatus"],["Velocity","velocity"],["verilog",
"verilog"],["VGL","vgl"],["vhdl","vhdl"],["VimL","vim"],["X10","x10"],["XML","xml"],["XQuery","xquery"],["XSLT","xslt"],["Xtend","xtend"],["XUL+mozpreproc","xul+mozpreproc"],["YAML","yaml"],["YAML+Jinja","yaml+jinja"],["Zephir","zephir"]],XJ=z.ob(VJ,TJ);z.e=SJ.prototype;z.e.defaults={EU:"lang-select",ar:"collapsed",YQ:"lang-list",hT:"lang-option",yg:"active",nD:"checked"};z.e.D=function(){SJ.o.D.call(this);this.v().H();this.aa.H();z.O(this.h);this.Lr=this.Bu=this.h=null};
z.e.B=function(){var a=this.J;this.h=z.N("div",{innerHTML:this.template,className:[a.EU,a.ar].join(" ")})};z.e.template='\x3cdiv class\x3d"title-button"\x3e选择语言\x3c/div\x3e\x3ci class\x3d"zg-icon zg-icon-double-arrow"\x3e\x3c/i\x3e\x3cdiv class\x3d"input-wrapper"\x3e\x3cinput class\x3d"filter-input zg-form-text-input" placeholder\x3d"搜索语言"\x3e\x3c/div\x3e';
z.e.C=function(){SJ.o.C.call(this);this.Bu=z.L("title-button",this.h);this.Lr=z.L("filter-input",this.h);z.xo(this.Bu,!0);YJ(this,this.Lr,this.h);this.v().g(this.h,"click",this.zl).g(this.Bu,"click",this.EP)};z.e.Y=function(){return this.le};z.e.Da=function(a){var b=a&&z.rb(XJ,function(b){return b.value===a});b&&(this.pk(b.label),this.dispatchEvent({type:"change",gT:b}));this.le=a};
z.e.zl=function(a){var b=this.aa,c=b.M.m();c&&window.document.activeElement!==this.Lr&&!c.contains(a.target)&&(a.preventDefault(),a.stopPropagation(),z.os(b))};z.e.EP=function(){this.isCollapsed()&&this.wi(!1)};z.e.Qr=function(){return this.aa};z.e.isCollapsed=function(){return z.V.has(this.h,this.J.ar)};z.e.wi=function(a){if(this.isCollapsed()!==a){var b=this.Lr,c=this.J;a?z.V.add(this.h,c.ar):(z.V.remove(this.h,c.ar),a=this.aa,c=a.M,a.im(XJ),c.m().scrollTop=0,c.show(),b.value="",b.focus())}};
z.e.pk=function(a){var b=this.Bu;b.title=a;z.nf(b,a)};z.e.Jz=function(a){this.Da(a.value);this.aa.Bc()};z.v(ZJ,z.nz);var lK=z.C||z.vg||z.A;z.e=ZJ.prototype;z.e.ld=z.jb("CodePlugin");z.e.Ge=function(a){return"+code"===a};z.e.ef=function(a){this.Ge(a)&&this.trigger()};z.e.queryCommandValue=function(){var a="1"===gK(this).state,b=this.F.Pb.EnterHandler;b&&(a?b.disable(this.F):b.enable(this.F));eK(this,a);return a};z.e.defaults={qN:""};z.e.PU=function(a){this.Eb=a;this.ex=["toggleFullScreen"].concat("+code")};z.e.D=function(){ZJ.o.D.call(this);this.Eb=null};
z.e.trigger=function(){var a=gK(this),b=a.Qt,c=a.code;switch(a.state){case "1":var d=!(0,z.cb)(z.Go(c)),a=OH(c);d?(c.parentNode.removeChild(c),a&&z.Hu(a,!0)):(b=sH(b),d=z.Na(c.innerHTML),z.zu(z.Wo(new z.wu(c,!1,!0),z.Au))&&(d="\x3cbr\x3e"+d),a&&"BR"!==a.tagName&&(d+="\x3cbr\x3e"),a=z.Xe(d),c.parentNode.replaceChild(a,c),b.restore());break;case "2":c=oK,a=(0,z.cb)(b.Jd())?dK(b.Xf()):lK?"\n":"",c(this,b,a)}};
z.e.qn=function(a,b){var c=window.document.createElement(a);c.id=z.Xg(z.Wg.ba());return b(c,function(){c=z.I(c.id);c.removeAttribute("id");return c})};z.e.xg=function(){var a=this.F;this.Nm=cK(this.F.Ea);z.Bc(a,this.Nm);z.E(a,"delayedchange",this.eU,!1,this);z.E(a.Ea,"paste",this.Zx,!1,this)};z.e.eU=function(){var a=this.Nm&&this.Nm.Fx();a&&a.V()&&a.anchor&&a.ha()};
z.e.Zx=function(a){var b=gK(this),c=b.Qt,d=b.code;if("1"===b.state)if(b=a.fc.clipboardData)b.types&&z.y(b.types,"text/plain")&&(a.preventDefault(),b=b.getData("text/plain"),hK(c,b));else if(window.clipboardData){if(b=window.clipboardData.getData("Text"))a.preventDefault(),iK(this,c,b)}else{var f=c.va();a=c.Jd().length;var g=(d.firstChild?z.Du(d.firstChild):0)-f-a;(0,window.setTimeout)(function(){var a=dK(d.innerHTML);z.nf(d,a);a=(d.firstChild?z.Du(d.firstChild):0)-g;d.firstChild&&z.uu(d.firstChild,
Math.max(f,a)).select()})}};z.e.Xx=function(a){if(13===a.keyCode)return this.Tx(a);if(40===a.keyCode)return kK(this)};z.e.Tx=function(a){var b=gK(this),c=b.Qt;if("1"===b.state)return a.preventDefault(),z.B?nK(this,c):window.document.queryCommandSupported("insertLineBreak")?window.document.execCommand("insertLineBreak"):(a=window.document.createTextNode("\n"),c.insertNode(a),z.Hu(a)),this.F.bf(),!0};z.tG["+code"]={hb:!0,S:"插入代码",Aa:"+code",Na:"tr-icon tr-code",factory:z.iE};z.v(qK,z.nz);var WK=/^(DIV|TR|LI|BLOCKQUOTE|H\d|PRE|XMP)/;z.e=qK.prototype;z.e.ld=function(){return"RemoveFormatting"};z.e.Ge=function(a){return"+removeFormat"==a};z.e.ef=function(a){"+removeFormat"==a&&sK(this)};z.e.ds=function(a,b,c){return c?" "==b?(this.F.execCommand("+removeFormat"),!0):!1:!1};
z.e.DI=function(a){var b=window.document.createElement("DIV");b.innerHTML=a;a=[];for(var b=[b.childNodes,0],c=[],d=0,f=[],g=0,h=0;0<=h;h-=2){for(var k=!1;0<g&&h<=f[g-1];)g--,k=!0;k&&rK(a);for(k=!1;0<d&&h<=c[d-1];)d--,k=!0;k&&rK(a);for(var k=b[h],m=b[h+1];m<k.length;){var n=k[m++],t=n.nodeName,x=this.hF(n);if(null!=x)a.push(x);else{switch(t){case "#text":n=0<d?n.nodeValue:z.lp(n.nodeValue);n=z.Oa(n);a.push(n);continue;case "P":rK(a);rK(a);break;case "BR":rK(a);continue;case "TABLE":rK(a);f[g++]=h;
break;case "PRE":case "XMP":c[d++]=h;break;case "STYLE":case "SCRIPT":case "SELECT":continue;case "A":if(n.href&&""!=n.href){a.push("\x3ca href\x3d'");a.push(n.href);a.push("'\x3e");a.push(this.DI(n.innerHTML));a.push("\x3c/a\x3e");continue}else break;case "IMG":a.push("\x3cimg src\x3d'");a.push(n.src);a.push("'");"0"==n.border&&a.push(" border\x3d'0'");a.push("\x3e");continue;case "TD":n.previousSibling&&a.push(" ");break;case "TR":n.previousSibling&&rK(a);break;case "DIV":if(x=n.parentNode,x.firstChild==
n&&WK.test(x.tagName))break;default:WK.test(t)&&rK(a)}n=n.childNodes;0<n.length&&(b[h++]=k,b[h++]=m,k=n,m=0)}}}return a.join("").replace(/\xa0|[ \t]+/g," ")};z.e.hF=function(){return null};z.v(vK,qK);vK.prototype.hF=function(a){var b;if("IMG"!==a.nodeName)return null;b=[];b.push('\x3cimg src\x3d"');b.push(z.Oa(a.src));b.push('"');a.getAttribute("eeimg")&&a.getAttribute("alt")&&b.push(' eeimg\x3d"'+z.Oa(a.getAttribute("eeimg"))+'" alt\x3d"'+z.Oa(a.getAttribute("alt"))+'"');b.push("\x3e");return b.join("")};z.v(wK,UH);z.v(xK,z.Mc);z.e=wK.prototype;z.e.template=(0,z.Av)('\x3cdiv class\x3d"zm-img-uploader"\x3e\x3ciframe src\x3d"about:blank" name\x3d"av_up_frame" style\x3d"position: absolute; height: 0; width: 0; left: -9000px; "\x3e\x3c/iframe\x3e\x3cdiv class\x3d"zg-section zm-img-uploader-tab"\x3e\x3ca href\x3d"javascript:;" class\x3d"tab-nav selected"\x3e上传图片\x3c/a\x3e 或 \x3ca href\x3d"javascript:;" class\x3d"tab-nav"\x3e引用站外图片\x3c/a\x3e\x3c/div\x3e\x3cform class\x3d"zg-clear" target\x3d"av_up_frame" method\x3d"POST" enctype\x3d"multipart/form-data" action\x3d"\x3c%\x3d uploadURL %\x3e"\x3e\x3cdiv class\x3d"tab-content selected \x3c% if (canStylize) { %\x3einline\x3c% } %\x3e"\x3e\x3c% if (canStylize) { %\x3e\x3cinput type\x3d"file" name\x3d"upload_file" style\x3d"opacity:0;height:0;width:0;font-size:0;position:absolute;"\x3e\x3ca href\x3d"javascript:;" class\x3d"browser zg-btn-blue"\x3e选择图片\x3c/a\x3e\x3c% } else { %\x3e\x3cinput type\x3d"file" name\x3d"upload_file"\x3e\x3c% } %\x3e\x3c/div\x3e\x3cdiv class\x3d"tab-content"\x3e\x3cinput type\x3d"text" autocomplete\x3d"off" name\x3d"upload_file_url" class\x3d"zm-editable-editor-input zg-form-text-input"\x3e\x3ca href\x3d"javascript:;" class\x3d"insert zg-btn-blue zm-uploader-button-fix"\x3e确认\x3c/a\x3e\x3c/div\x3e\x3cspan style\x3d"display: none; " class\x3d"zm-img-uploader-loading"\x3e正在上传\x3c/span\x3e\x3cspan style\x3d"display: none; " class\x3d"zm-img-uploader-error"\x3e上传图片失败，请稍后重试\x3c/span\x3e\x3c/form\x3e\x3cdiv class\x3d"zg-gray"\x3e请不要上传与回答问题无关的图片，详细请看 \x3ca href\x3d"/question/20064580" target\x3d"_blank"\x3e知乎图片使用规范\x3c/a\x3e\x3c/div\x3e\x3cdiv class\x3d"zm-command"\x3e\x3ca class\x3d"cancel" href\x3d"javascript:;"\x3e取消\x3c/a\x3e\x3c/div\x3e\x3c/div\x3e');
z.e.vw=function(){var a=z.Xe(this.template({uploadURL:this.BB,canStylize:this.IM}));z.Eb({form:"form",eB:".zm-img-uploader-tab",ah:".zm-img-uploader-loading",df:".zm-img-uploader-error",DJ:"input[type\x3dtext]",Gn:"input[type\x3dfile]",aD:".browser",hw:".cancel",wQ:".insert"},function(b,d){this[d]=(0,window.$)(b,a).get(0)},this);this.T.g(z.X,"iframe_data",this.Ev).g(this.Gn,"change",this.zT).g(this.wQ,"click",this.xQ).g(this.hw,"click",function(){this.Tn();this.hide()}).g(this.eB,"click",function(a){a=
(0,window.$)(a.target);a.is("a")&&!a.is(".selected")&&yK(this,a.index())});this.BD=a;z.Vm||(yK(this,1),(0,window.$)(this.eB).replaceWith("\x3cstrong\x3e输入站外图片地址：\x3c/strong\x3e"));this.aD&&this.T.g(this.aD,"click",function(){this.Gn.click()});var b=new VH(this);b.La("插入图片").ia(this.BD);b=YH(b);z.Kj(b,null);return b};z.e.zT=function(){this.Gn.value&&(PH(this.Gn.value)?(this.DJ.value="",z.P(this.ah,!0),z.P(this.df,!1),this.form.submit()):zK(this,"图片不是 .jpg 或 .png 格式无法上传"))};
z.e.xQ=function(){var a=z.qr(this.DJ.value);a?z.Ka(a,"http://")?(this.Gn.value="",z.P(this.ah,!0),z.P(this.df,!1),this.form.submit()):zK(this,"我们目前不支持该协议。"):zK(this,"请填写图片地址。")};z.e.Ev=function(a){z.P(this.ah,!1);this.pm(a.uf)};z.e.pm=function(a){a&&!a.r?(this.dispatchEvent(this.sn(a.msg)),this.hide()):zK(this,a.msg)};z.e.sn=function(a){return new xK(a)};z.e.D=function(){this.T.H();this.T=null;wK.o.D.call(this)};z.v(AK,$H);z.e=AK.prototype;z.e.ld=z.jb("ImageDialogPlugin");
z.e.ef=function(a,b){var c=this.F;return c.rf||(c.Tf(),c.rf)?AK.o.ef.call(this,a,b):!1};z.e.Bj=function(a){if(a&&"mouseup"===a.type){var b=a.target;b&&"IMG"===b.nodeName&&(a=OH(b),a||(a=window.document.createElement("br"),z.cf(a,b)),z.Gu(a))}};z.e.Sn=function(a){AK.o.Sn.call(this,a)};z.e.uw=function(a){a=new wK(a);this.T.g(a,"ok",this.Xn).g(a,"cancel",this.Ox);return a};z.e.D=function(){AK.o.D.call(this);this.T.H()};
z.e.Xn=function(a){aI(this);var b=pH(this),c;c=a.aI?b.B("IMG",{"class":"origin_image zh-lightbox-thumb","data-original":a.aI,title:"点击查看原图",src:a.Ll}):b.B("IMG",{"class":"content_image",src:a.Ll});a.xI&&c.setAttribute("data-rawwidth",a.xI);a.wI&&c.setAttribute("data-rawheight",a.wI);a=z.Oz(this.F);if(HH(a))a.kg(c),z.B||(z.Hu(c,!1),b.Ta().focus()),z.Pz(this.F),this.F.bf();else return null;this.T.removeAll()};z.e.Ox=function(){this.T.removeAll()};z.v(BK,UH);z.v(CK,z.Mc);z.e=BK.prototype;z.e.show=function(){BK.o.show.call(this);this.Nu.focus()};z.e.hide=function(){BK.o.hide.call(this)};
z.e.vw=function(){var a=z.sm.Lu+"/upload_video",a=this.jd.B("div","zm-img-uploader zm-img-uploader-upload-tab-selected",[this.jd.B("div","zg-section",this.jd.B("strong",null,"输入视频页地址：")),this.jd.B("iframe",{id:"video_up_frame",src:"about:_blank",name:"video_up_frame",style:"visible:hidden;position:absolute;height:0;width:0;left:-9000px"}),this.QE=this.jd.B("form",{"class":"zg-section-title",target:"video_up_frame",method:"post",enctype:"multipart/form-data",action:a},[this.Nu=this.jd.B("input",{type:"text",
"class":"zg-form-text-input",name:"upload_file_url",autocomplete:"off"}),this.nn=this.jd.B("a",{"class":"zg-btn-blue zm-uploader-button-fix",name:"save",href:"javascript:;"},"确定"),this.jd.B("div","zm-video-uploader-info",[this.ah=this.jd.B("span",{style:"display:none","class":"zm-img-uploader-loading"},"正在上传"),this.df=this.jd.B("span",{style:"display:none","class":"zm-img-uploader-error"},"插入视频失败，请稍后重试")])]),this.hQ=this.jd.B("div","zg-gray"),this.ln=this.jd.B("div","zm-command",[this.hw=this.jd.B("a",
{href:"javascript:;"},"取消")])]);this.hQ.innerHTML='我们目前支持\x3ca class\x3d"zg-link-gray" target\x3d"_blank" href\x3d"http://youku.com"\x3e优酷\x3c/a\x3e、\x3ca class\x3d"zg-link-gray" target\x3d"_blank" href\x3d"http://tudou.com"\x3e土豆\x3c/a\x3e、\x3ca href\x3d"http://video.sina.com.cn/" class\x3d"zg-link-gray" target\x3d"_blank"\x3e新浪\x3c/a\x3e、\x3ca href\x3d"http://v.qq.com/" class\x3d"zg-link-gray" target\x3d"_blank"\x3e腾讯\x3c/a\x3e、\x3ca href\x3d"http://www.56.com/" class\x3d"zg-link-gray" target\x3d"_blank"\x3e56\x3c/a\x3e、\x3ca href\x3d"http://tv.sohu.com/" class\x3d"zg-link-gray" target\x3d"_blank"\x3e搜狐\x3c/a\x3e、\x3ca href\x3d"http://www.iqiyi.com/" class\x3d"zg-link-gray" target\x3d"_blank"\x3e爱奇艺\x3c/a\x3e视频服务。\x3cbr /\x3e请不要上传与回答问题无关的视频，详细请看 \x3ca href\x3d"http://www.zhihu.com/question/20118966" target\x3d"_blank"\x3e知乎视频使用规范\x3c/a\x3e';
this.T.g(this.hw,"click",function(){this.Tn();this.hide()}).g(this.nn,"click",this.jI).g(this.ln,"click",this.Oa).g(this.QE,"submit",function(){return DK(this,this.Nu.value)}).g(z.X,"iframe_data",this.Ev);this.BD=a;var b=new VH(this);b.La("插入视频").ia(a);a=YH(b);z.Kj(a,null);return a};z.e.jI=function(){if(this.Nu.value){var a=z.qr(this.Nu.value);a&&DK(this,a)&&(z.P(this.ah,!0),z.P(this.df,!1),this.QE.submit())}};z.e.Oa=function(a){"save"===(a.target&&a.target.name)&&this.jI()};
z.e.Ev=function(a){z.P(this.ah,!1);this.pm(a.uf)};z.e.pm=function(a){a&&!a.r?(this.dispatchEvent(this.sn(a.msg[0],a.msg[1],a.msg[2],a.msg[3],a.msg[4])),this.hide()):(a=a.msg,z.P(this.ah,!1),this.df.innerHTML=a,z.P(this.df,!0))};z.e.sn=function(a,b,c,d,f){return new CK(a,b,c,d,f)};z.e.D=function(){this.T.H();this.T=null;BK.o.D.call(this)};z.v(EK,$H);z.e=EK.prototype;z.e.ld=z.jb("VideoDialogPlugin");z.e.ef=function(a,b){var c=this.F;return c.rf||(c.Tf(),c.rf)?EK.o.ef.call(this,a,b):!1};
z.e.Sn=function(a){EK.o.Sn.call(this,a)};z.e.uw=function(a){a=new BK(a);this.T.g(a,"ok",this.Xn).g(a,"cancel",this.Ox);return a};z.e.D=function(){EK.o.D.call(this);this.T.H()};
z.e.Xn=function(a){aI(this);var b=pH(this),c=b.B("a",{"class":"video-link",href:a.eV,"data-src":a.fW,"data-name":a.jK,"data-poster":a.poster,"data-videoid":a.eW});z.nf(c,a.jK);a=z.Io(c);a=z.Xe(a+" ");var c=a.firstChild,d=z.Oz(this.F);if(HH(d))d.kg(a),z.B?window.document.selection&&(b=window.document.selection.createRange(),b.move("character",-1),b.select()):(z.Hu(c),b.Ta().focus()),z.Pz(this.F),this.F.bf();else return null;this.T.removeAll()};z.e.Ox=function(){this.T.removeAll()};z.rz=!0;(function(a){z.nz.prototype.execCommand=function(b){var c=this.F;return z.Wn(KK,b)&&!c.rf?(c.Tf(),!1):a.apply(this,arguments)}})(z.nz.prototype.execCommand);(function(a,b){$H.prototype.execCommand=function(c){var d=this.F;return!z.y(b,c)||d.rf||(d.Tf(),d.rf)?a.apply(this,arguments):!1}})($H.prototype.execCommand,["+equation"]);FK="video";JK=z.Vc?"⌘":"ctrl";z.tG[FK]={Aa:FK,S:"插入视频",Na:"tr-icon tr-video",factory:z.gE};z.tG["+equation"]={Aa:"+equation",S:{}.WW,Na:"tr-icon tr-equation",factory:z.gE};
z.tG["+bold"].S="粗体 ("+JK+"+b)";z.tG["+italic"].S="斜体 ("+JK+"+i)";z.tG["+underline"].S="下划线 ("+JK+"+u)";z.tG["+superscript"].S="引用内容";z.tG["+insertOrderedList"].S="有序列表";z.tG["+insertUnorderedList"].S="无序列表";z.tG["+removeFormat"].S="清除格式";z.tG.image.S="插入图片";z.tG[FK].S="插入视频";z.tG["+equation"].S="插入公式";z.la(GK);
GK.prototype.Ze=function(a,b){this.config=b;var c,d,f;d=z.L("zm-editable-toolbar-container",a);c=z.L("zm-editable-editor-outer",a);f=z.L("zm-editable-editor-field-element",a);var g=new z.Wz(f.id);g.xM=89;var h=HK(d,b);new GJ(g,h);z.Bc(g,h);nH(g,new iI);nH(g,new vJ);if(b.loremIpsum_&&(nH(g,new xJ(b.loremIpsum_)),z.A))g.on("load",function(){z.md(g.m(),"focus",function(){g.execCommand("clearlorem",!0)})});nH(g,new JI);nH(g,new vK);nH(g,new BJ);d=new ZJ;nH(g,d);nH(g,new AK);nH(g,new EK);nH(g,new JJ);
nH(g,new tJ);nH(g,new aJ);nH(g,new OJ);b.enableFullScreen&&(c=new z.qE({title:"写作模式",xk:c}),nH(g,c));g.on("load",function(){b.useScraper_&&IK(g,h)},!1,this);return[g,h]};z.Fa("ZH.createRichTextEditor",function(a,b){return GK.ba().Ze(a,b)});z.kg("richtexteditor");}).call(this, __z_z__);
//# sourceURL=/static/revved/-/js/closure/richtexteditor.ded26972.js